package:
  name: airflow
  version: 2.10.3
  epoch: 1
  description: Platform to programmatically author, schedule, and monitor workflows
  options:
    #  There is a dependency on libarrow.so although it
    #  is provided in the virtual environment. Enabling no-depends
    #  works around this
    no-depends: true
  dependencies:
    runtime:
      - python3
  copyright:
    - license: Apache-2.0

environment:
  contents:
    packages:
      - gcc
      - glibc-dev
      - mariadb-connector-c-dev
      - mariadb-dev
      - nodejs
      - openssf-compiler-options
      - pkgconf-dev
      - postgresql-dev
      - py3-pip
      - py3-xmlsec
      - python3
      - python3-dev
      - wolfi-base
      - xmlsec-dev
      - xmlsec-openssl
      - yarn

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/apache/airflow
      tag: ${{package.version}}
      expected-commit: c99887ec11ce3e1a43f2794fcf36d27555140f00

  - runs: |
      # by default airflow celery provider is not built,but running the upstream helm chart requires it
       python patch.py
       # remove the patcher
       rm -rf patch.py

  - uses: patch
    with:
      patches: requests.patch urllib3.patch

  - runs: |
      # requires EPOCH to be later that 1980
      export SOURCE_DATE_EPOCH=315532800

      python -m venv venv --system-site-packages
      source venv/bin/activate

      pip install build

      # To install mysqlclient wheel
      export MYSQLCLIENT_CFLAGS=`mysql_config --cflags`
      export MYSQLCLIENT_LDFLAGS=`mysql_config --libs`

      python -m build --wheel
      pip install dist/*.whl

  - runs: |
      # CVE-2024-6345 GHSA-cx63-2mw6-8hw5
      # setuptools comes from airflow/providers/google/provider.yaml having
      # gcloud-aio-auth>=4.0.0,<5.0.0 . gcloud-aio-auth 4 is backlevel and has
      # setuptools in it's pyproject.toml 'tool.poetry.dependencies'
      # The tldr; For that case it is not needed in runtime.
      ./venv/bin/pip uninstall --yes setuptools

      #GHSA-8w49-h785-mj3c/GHSA-8495-4g3g-x7pr/GHSA-27mf-ghqm-j3j8 fixes
      ./venv/bin/pip install aiohttp==3.10.11
      ./venv/bin/pip install tornado==6.4.2

  - working-directory: venv/lib/python3.12/site-packages/airflow/www
    runs: |
      # front-end build
      yarn install --frozen-lockfile
      yarn run build
      rm -rf node_modules

  - runs: find . -name '__pycache__' -exec rm -rf {} +

  - runs: |
      mkdir -p ${{targets.destdir}}/opt/airflow/dags
      mkdir -p ${{targets.destdir}}/scripts/docker

      # The first time you run Airflow, it will create a file called `airflow.cfg` in
      # `$AIRFLOW_HOME` directory
      # However, for production case it is advised to generate the configuration
      venv/bin/airflow config list --defaults > ${{targets.destdir}}/"airflow.cfg"

      mv venv ${{targets.destdir}}/opt/airflow
      rm -rf ${{targets.destdir}}/opt/airflow/venv/bin/__pycache*
      sed -i "s|/home/build|/opt/airflow|g" ${{targets.destdir}}/opt/airflow/venv/bin/*

      cp airflow/config_templates/default_webserver_config.py ${{targets.destdir}}/

      cp scripts/docker/entrypoint_prod.sh ${{targets.destdir}}/entrypoint
      chmod 755 ${{targets.destdir}}/entrypoint

      cp scripts/docker/clean-logs.sh ${{targets.destdir}}/clean-logs
      chmod 755 ${{targets.destdir}}/clean-logs

      cp scripts/docker/airflow-scheduler-autorestart.sh ${{targets.destdir}}/airflow-scheduler-autorestart
      chmod 755 ${{targets.destdir}}/airflow-scheduler-autorestart

      cp -r scripts/docker/* ${{targets.destdir}}/scripts/docker
      chmod 755 ${{targets.destdir}}/scripts/docker

update:
  enabled: true
  ignore-regex-patterns:
    - 'rc\d+$'
    - 'helm-chart*'
  github:
    identifier: apache/airflow

test:
  environment:
    contents:
      packages:
        - python3
  pipeline:
    - runs: |
        export PATH=/opt/airflow/venv/bin:$PATH
        HOME=/home/build airflow version
