package:
  name: authservice
  version: 1.0.3
  epoch: 1
  description: Move OIDC token acquisition out of your app code and into the Istio mesh
  copyright:
    - license: Apache-2.0

environment:
  environment:
    CGO_ENABLED: "0"

pipeline:
  - uses: git-checkout
    with:
      expected-commit: adea4ec0bdc9cd756622a6f0234473100be4a377
      repository: https://github.com/istio-ecosystem/authservice
      tag: v${{package.version}}

  - uses: go/bump
    with:
      deps: golang.org/x/crypto@v0.31.0

  - uses: go/build
    with:
      packages: ./cmd
      ldflags: -s -w
      output: authservice

  - uses: strip

subpackages:
  - name: ${{package.name}}-compat
    pipeline:
      - runs: |
          mkdir -p "${{targets.contextdir}}/usr/local/bin"
          ln -s /usr/bin/authservice "${{targets.contextdir}}/usr/local/bin/authservice"

update:
  enabled: true
  github:
    identifier: istio-ecosystem/authservice
    strip-prefix: v

test:
  pipeline:
    - runs: |
        authservice -v
        authservice --version
        authservice --help
