package:
  name: aws-c-event-stream
  version: 0.5.0
  epoch: 1
  description: "AWS C99 implementation of the vnd.amazon.eventstream content-type"
  copyright:
    - license: Apache-2.0

environment:
  contents:
    packages:
      - aws-c-cal-dev
      - aws-c-common-dev
      - aws-c-io-dev
      - aws-checksums-dev
      - build-base
      - busybox
      - ca-certificates-bundle
      - cmake
      - openssf-compiler-options
      - openssl-dev
      - s2n-tls-dev
      - samurai

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/awslabs/aws-c-event-stream
      tag: v${{package.version}}
      expected-commit: d2dcc9344dae24de320866045d85166d8a91a0d1

  - runs: |
      if [ "$CBUILD" != "$CHOST" ]; then
        CMAKE_CROSSOPTS="-DCMAKE_SYSTEM_NAME=Linux -DCMAKE_HOST_SYSTEM_NAME=Linux"
      fi
      CFLAGS="$CFLAGS -flto=auto" \
      CXXFLAGS="$CXXFLAGS -flto=auto" \
      cmake -B build -G Ninja \
        -DCMAKE_INSTALL_PREFIX=/usr \
        -DCMAKE_INSTALL_LIBDIR=/usr/lib \
        -DBUILD_SHARED_LIBS=True \
        -DCMAKE_BUILD_TYPE=None \
        -DBUILD_TESTING="OFF" \
        $CMAKE_CROSSOPTS
      cmake --build build

  - runs: |
      DESTDIR="${{targets.destdir}}" cmake --install build

  - uses: strip

subpackages:
  - name: aws-c-event-stream-dev
    pipeline:
      - uses: split/dev
      - runs: |
          mkdir -p "${{targets.subpkgdir}}"/usr/lib
          mv "${{targets.destdir}}"/usr/lib/aws-c-event-stream "${{targets.subpkgdir}}"/usr/lib/
    dependencies:
      runtime:
        - aws-c-event-stream
    description: aws-c-event-stream dev

test:
  pipeline:
    - uses: test/ldd-check
      with:
        files: /usr/lib/libaws-c-event-stream.so.1.0.0

update:
  enabled: true
  github:
    identifier: awslabs/aws-c-event-stream
    strip-prefix: v
    use-tag: true
