package:
  name: azcopy
  version: 10.27.1
  epoch: 1
  description: The new Azure Storage data transfer utility
  copyright:
    - license: MIT

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/Azure/azure-storage-azcopy
      tag: v${{package.version}}
      expected-commit: 741ca876e9874f2f169fbfb355c123fe39337081

  - uses: go/bump
    with:
      deps: golang.org/x/crypto@v0.31.0

  - uses: go/build
    with:
      packages: .
      output: azcopy
      go-package: go

update:
  enabled: true
  github:
    identifier: Azure/azure-storage-azcopy
    strip-prefix: v

test:
  pipeline:
    - runs: |
        azcopy --version
        azcopy --help
