package:
  name: btrfs-progs
  version: "6.12"
  epoch: 1
  description: BTRFS filesystem utilities
  copyright:
    - license: GPL-2.0-or-later

vars:
  py-version: 3.13

environment:
  contents:
    packages:
      - asciidoc
      - autoconf
      - automake
      - build-base
      - busybox
      - ca-certificates-bundle
      - e2fsprogs-dev
      - libgcrypt-dev
      - linux-headers
      - lzo-dev
      - openssf-compiler-options
      - pkgconf-dev
      - py${{vars.py-version}}-setuptools
      - py3-build-base-dev
      - python-${{vars.py-version}}-dev
      - systemd-dev
      - zlib-dev
      - zstd-dev

pipeline:
  - uses: fetch
    with:
      uri: https://www.kernel.org/pub/linux/kernel/people/kdave/btrfs-progs/btrfs-progs-v${{package.version}}.tar.xz
      expected-sha512: 57da37f460a33b5f5232a5c8e67eb5976fb13483a1437112bd433b179bc0e497a1aadfe24705eb4fb4e0a98d2a33fd3c46808b3ca161421475442a70b964c446

  - uses: autoconf/configure
    with:
      opts: |
        --with-crypto=libgcrypt \
        --disable-backtrace \
        --disable-documentation # documentation requires a _ton_ of python3 dependencices that should be added to sphinx instead

  - uses: autoconf/make

  - uses: autoconf/make-install

  - uses: strip

subpackages:
  - name: btrfs-progs-dev
    pipeline:
      - uses: split/dev
    dependencies:
      runtime:
        - btrfs-progs
    description: btrfs-progs dev
    test:
      pipeline:
        - uses: test/pkgconf

  - name: py3-btrfs-progs
    description: Python 3 bindings for btrfs-progs
    dependencies:
      runtime:
        - btrfs-progs
    pipeline:
      - runs: |
          make install_python DESTDIR="${{targets.subpkgdir}}"
    test:
      pipeline:
        - uses: python/import
          with:
            import: btrfsutil

  - name: btrfs-progs-bash-completion
    description: btrfs-progs bash completion
    pipeline:
      - runs: |
          _out="${{targets.subpkgdir}}"/usr/share/bash-completion/completions
          mkdir -p $_out
          install -Dm644 btrfs-completion $_out

update:
  enabled: true
  release-monitor:
    identifier: 227

test:
  pipeline:
    - runs: |
        btrfs --version
        btrfs-convert --help
        btrfs-find-root --help
        btrfs-image --help
        btrfsck --help
        btrfstune --help
        fsck.btrfs --version
        mkfs.btrfs --version
        btrfs --help
        fsck.btrfs --help
        mkfs.btrfs --help
    - name: "Create and inspect test filesystem image"
      runs: |
        # Create 120MB test image (minimum size is ~109MB)
        dd if=/dev/zero of=test.img bs=1M count=120
        mkfs.btrfs -f test.img

        # Verify filesystem
        btrfs check test.img

        # Show filesystem info
        btrfs inspect-internal dump-super test.img
    - uses: test/ldd-check
      with:
        files: |-
          /usr/lib/libbtrfs.so.0
          /usr/lib/libbtrfs.so.0.1
          /usr/lib/libbtrfs.so.0.1.4
          /usr/lib/libbtrfsutil.so.1
          /usr/lib/libbtrfsutil.so.1.3
          /usr/lib/libbtrfsutil.so.1.3.2
