package:
  name: buildah
  version: 1.38.0
  description: "A tool that facilitates building OCI images"
  epoch: 1
  copyright:
    - license: Apache-2.0

environment:
  contents:
    packages:
      - busybox
      - ca-certificates-bundle
      - go
      - gpgme-dev
      - libassuan-dev
      - libgpg-error-dev
      - libseccomp-dev
      - libseccomp-static
      - openssf-compiler-options

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/containers/buildah
      tag: v${{package.version}}
      expected-commit: 7aa3b5ee0470647fcf125930913132fe7c556bcd

  - uses: go/bump
    with:
      deps: golang.org/x/crypto@v0.31.0

  - runs: |
      make
      make install PREFIX=${{targets.destdir}}

  - uses: strip

update:
  enabled: true
  github:
    identifier: containers/buildah
    strip-prefix: v
    tag-filter: v

test:
  pipeline:
    - name: Verify buildah installation
      runs: |
        buildah version | grep ${{package.version}} || exit 1
        buildah --version
        buildah --help
