package:
  name: cert-manager-istio-csr
  version: 0.13.0
  epoch: 1
  description: istio-csr is an agent that allows for Istio workload and control plane components to be secured using cert-manager.
  copyright:
    - license: Apache-2.0

pipeline:
  - uses: git-checkout
    with:
      expected-commit: 6418780c2e2101f0786a9272f60f388ec178cf8d
      repository: https://github.com/cert-manager/istio-csr/
      tag: v${{package.version}}

  - uses: go/bump
    with:
      deps: golang.org/x/crypto@v0.31.0

  - uses: go/build
    with:
      ldflags: -X github.com/cert-manager/istio-csr//internal/version.AppVersion=${{package.version}} -X github.com/cert-manager/istio-csr/internal/version.GitCommit=$(git rev-parse HEAD)
      output: cmd
      packages: ./cmd

update:
  enabled: true
  github:
    identifier: cert-manager/istio-csr
    strip-prefix: v

test:
  pipeline:
    - runs: |
        cmd --help
