package:
  name: cilium-cli
  version: 0.16.22
  epoch: 1
  description: CLI to install, manage & troubleshoot Kubernetes clusters running Cilium
  copyright:
    - license: Apache-2.0

environment:
  contents:
    packages:
      - busybox
      - ca-certificates-bundle
      - git
      - go

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/cilium/cilium-cli
      tag: v${{package.version}}
      expected-commit: c52e8c38e6d6235bd8e6e961199a984275547d6f
      destination: cilium-cli

  - uses: go/bump
    with:
      deps: golang.org/x/crypto@v0.31.0
      modroot: cilium-cli

  - runs: |
      cd cilium-cli
      make install
      install -Dm755  /usr/local/bin/cilium ${{targets.destdir}}/usr/bin/cilium

  - uses: strip

update:
  enabled: true
  github:
    identifier: cilium/cilium-cli
    strip-prefix: v

test:
  pipeline:
    - runs: |
        cilium help
        cilium version
        cilium --help
