package:
  name: clusterctl
  version: 1.9.3
  epoch: 0
  description: A command line tool to manage clusters created by cluster API
  copyright:
    - license: Apache-2.0
  dependencies:
    runtime:
      - ca-certificates-bundle

environment:
  contents:
    packages:
      - busybox
      - ca-certificates-bundle
      - go
  environment:
    CGO_ENABLED: "0"

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/kubernetes-sigs/cluster-api
      tag: v${{package.version}}
      expected-commit: cd279dd0c24c5472db45255e3805ae16c61e1432

  - uses: go/build
    with:
      packages: ./cmd/clusterctl
      ldflags: $(hack/version.sh)
      output: clusterctl

  - uses: strip

update:
  enabled: true
  github:
    identifier: kubernetes-sigs/cluster-api
    strip-prefix: v

test:
  pipeline:
    - name: Version Check
      runs: |
        clusterctl version
        clusterctl --help
