package:
  name: consul-k8s-1.6
  version: 1.6.1
  epoch: 1
  description: The consul-k8s includes first-class integrations between Consul and Kubernetes.
  copyright:
    - license: MPL-2.0
  dependencies:
    runtime:
      - go-discover
    provides:
      - consul-k8s=${{package.full-version}}

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/hashicorp/consul-k8s
      expected-commit: 7e1efe4d2e2de852449876999292eef843aa7bfc
      tag: v${{package.version}}

  - uses: go/bump
    with:
      deps: golang.org/x/crypto@v0.31.0
      modroot: ./cli

  - uses: go/bump
    with:
      deps: golang.org/x/crypto@v0.31.0
      modroot: ./control-plane

  - uses: go/build
    with:
      modroot: ./control-plane/cni
      output: consul-cni
      packages: .

  - uses: go/build
    with:
      modroot: ./control-plane
      output: consul-k8s-control-plane
      packages: .

subpackages:
  - name: ${{package.name}}-cli
    description: "CLI for interacting with Consul on Kubernetes"
    pipeline:
      - uses: go/build
        with:
          modroot: ./cli
          output: consul-k8s
          packages: .
    test:
      pipeline:
        - name: Verify help
          runs: |
            consul-k8s --help

update:
  enabled: true
  github:
    identifier: hashicorp/consul-k8s
    strip-prefix: v
    tag-filter-prefix: v1.6.

test:
  pipeline:
    - name: Verify help
      runs: |
        consul-cni --help
        consul-k8s-control-plane --help
        consul-cni --version
        consul-k8s-control-plane --version
