package:
  name: crossplane
  version: 1.18.1
  epoch: 1
  description: Cloud Native Control Planes
  copyright:
    - license: Apache-2.0

environment:
  environment:
    CGO_ENABLED: "0"

pipeline:
  - uses: git-checkout
    with:
      expected-commit: 0ca82e4f152067f69af11d907ab7b4a0a21fed37
      repository: https://github.com/crossplane/crossplane
      tag: v${{package.version}}

  - runs: |
      mkdir -p ${{targets.destdir}}/crds
      cp cluster/crds/* ${{targets.destdir}}/crds

      mkdir -p ${{targets.destdir}}/webhookconfigurations
      cp cluster/webhookconfigurations/* ${{targets.destdir}}/webhookconfigurations

  - uses: go/bump
    with:
      deps: golang.org/x/crypto@v0.31.0

  - uses: go/build
    with:
      output: crossplane
      packages: ./cmd/crossplane
      ldflags: -X github.com/crossplane/crossplane/internal/version.version=v${{package.version}}

  - uses: strip

subpackages:
  - name: crossplane-crank
    pipeline:
      - uses: go/build
        with:
          output: crank
          packages: ./cmd/crank
      - uses: strip
    test:
      pipeline:
        - runs: |
            crank --help

update:
  enabled: true
  github:
    identifier: crossplane/crossplane
    strip-prefix: v

test:
  pipeline:
    - name: version and help output
      runs: |
        crossplane --version
        crossplane --help
