package:
  name: dagger
  version: 0.15.1
  epoch: 0
  description: Application Delivery as Code that Runs Anywhere
  copyright:
    - license: Apache-2.0

environment:
  environment:
    CGO_ENABLED: 0

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/dagger/dagger
      tag: v${{package.version}}
      expected-commit: 196f232a4d6b2d1d3db5f5e040cf20b6a76a76c5

  - uses: go/build
    with:
      ldflags: |
        -s -w
        -X github.com/dagger/dagger/engine.Version=v${{package.version}}
        -X github.com/dagger/dagger/engine.Tag=v${{package.version}}
      output: dagger
      packages: ./cmd/dagger

  - uses: strip

update:
  enabled: true
  ignore-regex-patterns:
    - 'sdk'
    - 'helm'
  github:
    identifier: dagger/dagger
    strip-prefix: v
    use-tag: true

test:
  pipeline:
    - runs: |
        dagger version
        dagger --help
