package:
  name: dbmate
  version: 2.24.0
  epoch: 1
  description: A lightweight, framework-agnostic database migration tool.
  copyright:
    - license: MIT
  dependencies:
    runtime:
      - ca-certificates-bundle

environment:
  contents:
    packages:
      - busybox
      - ca-certificates-bundle
      - go
  environment:
    CGO_ENABLED: "0"

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/amacneil/dbmate
      tag: v${{package.version}}
      expected-commit: 1acb12f064feddfd37f97ff1a6c3f672e4a8765f

  - uses: go/bump
    with:
      deps: golang.org/x/crypto@v0.31.0

  - uses: go/build
    with:
      packages: ./
      ldflags: -s -w
      output: dbmate

  - uses: strip

update:
  enabled: true
  github:
    identifier: amacneil/dbmate
    strip-prefix: v

test:
  pipeline:
    - name: Verify dbmate installation
      runs: |
        dbmate --version
        dbmate --help
