package:
  name: descheduler
  version: 0.31.0
  epoch: 1
  description: Descheduler for Kubernetes
  copyright:
    - license: Apache-2.0

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/kubernetes-sigs/descheduler
      tag: v${{package.version}}
      expected-commit: b35e93ec7ac7b011e71daf364615248a0b3eb696

  - uses: go/bump
    with:
      deps: golang.org/x/crypto@v0.31.0

  - uses: go/build
    with:
      packages: ./cmd/descheduler
      ldflags: |
        -X sigs.k8s.io/descheduler/pkg/version.version=${{package.version}}
        -X sigs.k8s.io/descheduler/pkg/version.gitsha1=$(git rev-parse HEAD)
        -X sigs.k8s.io/descheduler/pkg/version.buildDate=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
        -X sigs.k8s.io/descheduler/pkg/version.gitbranch=$(git rev-parse --abbrev-ref HEAD)
      output: descheduler

subpackages:
  - name: ${{package.name}}-compat
    description: "Compatibility package to place binaries in the location expected by upstream helm charts"
    pipeline:
      - runs: |
          mkdir -p ${{targets.contextdir}}/bin/
          ln -sf /usr/bin/descheduler ${{targets.contextdir}}/bin/descheduler

update:
  enabled: true
  github:
    identifier: kubernetes-sigs/descheduler
    strip-prefix: v

test:
  environment:
    contents:
      packages:
        - curl
  pipeline:
    - uses: test/kwok/cluster
    - runs: |
        descheduler version
        descheduler --help
        # Scale the cluster further
        kwokctl scale node --replicas 3
        curl -fL -o policy.yaml https://raw.githubusercontent.com/kubernetes-sigs/descheduler/master/examples/policy.yaml
        descheduler --kubeconfig ~/.kube/config --policy-config-file policy.yaml
