package:
  name: docker-compose
  version: 2.32.0
  epoch: 0
  description: Define and run multi-container applications with Docker
  copyright:
    - license: Apache-2.0

environment:
  contents:
    packages:
      - bash
      - btrfs-progs-dev
      - build-base
      - busybox
      - ca-certificates-bundle
      - containerd
      - coreutils
      - go
      - libseccomp-dev
      - libtool
      - linux-headers
      - lvm2-dev
      - openssf-compiler-options

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/docker/compose
      tag: v${{package.version}}
      expected-commit: a20b69ac5b860f1aa270519e4d02207246d7cb6b

  - runs: |
      mkdir -p ${{targets.destdir}}/usr/bin
      DESTDIR=${{targets.destdir}}/usr/bin/ make build

test:
  environment:
    contents:
      packages:
        - docker-cli
  pipeline:
    - runs: |
        docker compose --help
        docker-compose --version

update:
  enabled: true
  github:
    identifier: docker/compose
    strip-prefix: v
    tag-filter: v
