package:
  name: doppler-kubernetes-operator
  version: 1.5.1
  epoch: 6
  description: Automatically sync secrets from Doppler to Kubernetes and auto-reload deployments when secrets change.
  copyright:
    - license: Apache-2.0

environment:
  contents:
    packages:
      - busybox
      - go

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/DopplerHQ/kubernetes-operator
      tag: "v${{package.version}}"
      expected-commit: e8745b967df372a07c04410162f8861a2315374f

  - uses: go/bump
    with:
      deps: github.com/gogo/protobuf@v1.3.2 github.com/prometheus/client_golang@v1.11.1 google.golang.org/protobuf@v1.33.0 golang.org/x/net@v0.23.0 github.com/golang-jwt/jwt/v4@v4.5.1 golang.org/x/crypto@v0.31.0

  - runs: |
      CGO_ENABLED=0 GO111MODULE=on GOOS=$(go env GOOS) GOARCH=$(go env GOARCH)

  - uses: go/build
    with:
      packages: .
      ldflags: -X 'github.com/DopplerHQ/kubernetes-operator/pkg/version.ControllerVersion=${{package.version}}'
      output: manager

  - uses: strip

update:
  enabled: true
  github:
    identifier: DopplerHQ/kubernetes-operator
    strip-prefix: v

test:
  pipeline:
    - runs: |
        manager --help
