package:
  name: eksctl
  version: 0.199.0
  epoch: 1
  description:
  copyright:
    - license: Apache-2.0
  dependencies:
    runtime:
      - ca-certificates-bundle

environment:
  contents:
    packages:
      - busybox
      - ca-certificates-bundle
      - go

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/weaveworks/eksctl
      expected-commit: 228a27121c9aa65ba96df2033003be5a08e439f5
      tag: v${{package.version}}

  - uses: go/bump
    with:
      deps: golang.org/x/crypto@v0.31.0 golang.org/x/net@v0.33.0

  - runs: |
      make binary
      mkdir -p ${{targets.destdir}}/usr/bin
      mv eksctl ${{targets.destdir}}/usr/bin/

  - uses: strip

update:
  enabled: true
  github:
    identifier: weaveworks/eksctl
    strip-prefix: v

test:
  pipeline:
    - name: Verify eksctl help command
      runs: |
        eksctl --help
        eksctl version
    - name: Verify eksctl create nodegroup error message
      runs: |
        eksctl create nodegroup 2>&1 | grep "Error: couldn't create node group filter from command line options: --cluster must be set"
