package:
  name: envoy-gateway
  version: 1.2.4
  epoch: 0
  description: Manages Envoy Proxy as a Standalone or Kubernetes-based Application Gateway
  copyright:
    - license: Apache-2.0

environment:
  contents:
    packages:
      - btrfs-progs-dev

pipeline:
  - uses: git-checkout
    with:
      expected-commit: 6ca4fe3c5f9f734b748d85da46f6d790c0377c86
      repository: https://github.com/envoyproxy/gateway
      tag: v${{package.version}}

  - uses: go/build
    with:
      packages: ./cmd/envoy-gateway
      ldflags: |
        -X github.com/envoyproxy/gateway/internal/cmd/version.envoyGatewayVersion=${{package.version}}
        -X github.com/envoyproxy/gateway/internal/cmd/version.gitCommitID=$(git rev-parse HEAD)
      output: envoy-gateway

subpackages:
  - name: ${{package.name}}-compat
    description: Compat package for envoy-gateway
    pipeline:
      - runs: |
          mkdir -p "${{targets.contextdir}}"/usr/local/bin
          ln -sf /usr/bin/envoy-gateway "${{targets.contextdir}}"/usr/local/bin/envoy-gateway

  - name: ${{package.name}}-egctl
    pipeline:
      - uses: go/build
        with:
          packages: ./cmd/egctl
          output: egctl
          ldflags: |
            -X github.com/envoyproxy/gateway/internal/cmd/version.envoyGatewayVersion=${{package.version}}
            -X github.com/envoyproxy/gateway/internal/cmd/version.gitCommitID=$(git rev-parse HEAD)
    test:
      pipeline:
        - runs: egctl version --remote=false | grep ${{package.version}}

test:
  pipeline:
    - name: version and help tests
      runs: |
        envoy-gateway version | grep ${{package.version}}
        envoy-gateway help

update:
  enabled: true
  github:
    identifier: envoyproxy/gateway
    strip-prefix: v
    tag-filter: v
