package:
  name: external-secrets-operator
  version: 0.12.1
  epoch: 0
  description: Integrate external secret management systems with Kubernetes
  copyright:
    - license: Apache-2.0

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/external-secrets/external-secrets
      tag: v${{package.version}}
      expected-commit: 21205d3a093f9081ec79a7b0d1a8703363e95f2f

  - uses: go/build
    with:
      go-package: go
      packages: .
      output: external-secrets

  - uses: strip

test:
  environment:
    contents:
      packages:
        - git
        - curl
  pipeline:
    - uses: test/kwok/cluster
    - name: Fetch the testdata from the source repo
      runs: |
        git clone --depth=1 https://github.com/external-secrets/external-secrets
    - name: Run a simple test of the external secrets operator against the testdata
      working-directory: external-secrets/deploy/crds
      runs: |
        kubectl apply -f bundle.yaml

        # Start the operator
        external-secrets --help
        external-secrets &
        sleep 5

        curl localhost:8080/metrics | grep secretstore

update:
  enabled: true
  github:
    identifier: external-secrets/external-secrets
    strip-prefix: v
    tag-filter: v
