package:
  name: extism
  version: 1.6.1
  epoch: 1
  description: The extism CLI is used to manage Extism installations
  copyright:
    - license: BSD-3-Clause

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - openssf-compiler-options

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/extism/cli
      tag: v${{package.version}}
      expected-commit: 490e40cf54da80a297b173a8fb4e6557af230b0f

  - uses: go/bump
    with:
      deps: golang.org/x/crypto@v0.31.0

  - uses: go/build
    with:
      modroot: extism
      packages: .
      output: extism

  - uses: strip

update:
  enabled: true
  github:
    identifier: extism/cli
    strip-prefix: v

test:
  pipeline:
    - runs: |
        extism -v
        extism lib install
        extism lib versions
        extism --version
        extism --help
