package:
  name: flannel
  version: 0.26.2
  epoch: 0
  description: flannel is a network fabric for containers, designed for Kubernetes
  copyright:
    - license: Apache-2.0

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - go

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/flannel-io/flannel
      tag: v${{package.version}}
      expected-commit: e810d96f557a0dc39125800f3d1ab56a0b9c40d1

  # Build with CGO_ENABLED=1 to include the UDP backend
  - runs: |
      CGO_ENABLED=0
      if [ "$(go env GOARCH)" = "amd64" ]; then
        CGO_ENABLED=1
      fi
      CGO_ENABLED=$(CGO_ENABLED) go build -o "${{targets.destdir}}"/usr/bin/flanneld \
        -ldflags '-s -w -extldflags "-static" -X github.com/flannel-io/flannel/pkg/version.version=${{package.version}}'

  - uses: strip

update:
  enabled: true
  github:
    identifier: flannel-io/flannel
    strip-prefix: v

test:
  pipeline:
    # AUTOGENERATED
    - runs: |
        flanneld --version
        flanneld --help
