package:
  name: gh
  version: 2.63.2
  epoch: 1
  description: GitHub's official command line tool
  copyright:
    - license: MIT

environment:
  contents:
    packages:
      - busybox
      - ca-certificates-bundle
      - go
  environment:
    CGO_ENABLED: "0"

pipeline:
  - uses: git-checkout
    with:
      expected-commit: d60e5ffba335281439d95749abb6f4c3b94fabdc
      repository: https://github.com/cli/cli
      tag: v${{package.version}}

  - uses: go/bump
    with:
      deps: golang.org/x/crypto@v0.31.0

  - runs: make install prefix=${{targets.destdir}}/usr

  - uses: strip

update:
  enabled: true
  github:
    identifier: cli/cli
    strip-prefix: v

test:
  pipeline:
    - runs: |
        gh --version
        gh --help
