#nolint:valid-pipeline-git-checkout-tag
package:
  name: go-discover
  version: 0_git20241212
  epoch: 1
  description: go-discover is a Go (golang) library and command line tool to discover ip addresses of nodes in cloud environments based on meta information like tags provided by the environment.
  copyright:
    - license: MPL-2.0

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/hashicorp/go-discover
      expected-commit: 5eb1507d16b4e0862b2dc84581c45704e46261cb
      branch: master

  - uses: go/bump
    with:
      deps: golang.org/x/crypto@v0.31.0

  - uses: go/build
    with:
      output: discover
      packages: ./cmd/discover

update:
  enabled: true
  git: {}
  schedule:
    period: daily
    reason: Upstream does not maintain tags or releases

test:
  pipeline:
    - name: Verify help
      runs: |
        discover --help
        discover version
