package:
  name: gomplate
  version: 4.2.0
  epoch: 1
  description: A go templating utility.
  copyright:
    - license: MIT

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - git
      - go
      - openssf-compiler-options
      - wolfi-baselayout

pipeline:
  - uses: git-checkout
    with:
      expected-commit: 020f6d1a276ef39beeea83e2513ccead940bfea3
      repository: https://github.com/hairyhenderson/gomplate
      tag: v${{package.version}}

  - uses: go/bump
    with:
      deps: golang.org/x/crypto@v0.31.0

  - runs: |
      mkdir -p ${{targets.destdir}}/usr/bin
      go build -o ${{targets.destdir}}/usr/bin \
        -ldflags "-w -s -X github.com/hairyhenderson/gomplate/v4/version.Version=${{package.version}} \
        -X github.com/hairyhenderson/gomplate/v4/version.GitCommit=$(git rev-parse --short HEAD)" \
        github.com/hairyhenderson/gomplate/v4/cmd/gomplate

      # Test that the binary can be run, since there have been issues with the
      # Go version used by the tool that only manifest at runtime.
      ${{targets.destdir}}/usr/bin/gomplate -i 'the answer is: {{ mul 6 7 }}'

update:
  enabled: true
  github:
    identifier: hairyhenderson/gomplate
    strip-prefix: v

test:
  pipeline:
    # AUTOGENERATED
    - runs: |
        gomplate --version
        gomplate --help
