package:
  name: grafana-alloy
  version: 1.5.1
  epoch: 1
  description: OpenTelemetry Collector distribution with programmable pipelines
  copyright:
    - license: Apache-2.0

environment:
  contents:
    packages:
      - busybox
      - ca-certificates-bundle
      - go
      - nodejs-18
      - openssf-compiler-options
      - systemd-dev
      - tzdata
      - yarn
  environment:
    # https://github.com/grafana/alloy/blob/f5043307c5b9bb6d94dbb0d3c4d2bc19139f4b63/Makefile#L89
    CGO_ENABLED: "1"

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/grafana/alloy
      tag: v${{package.version}}
      expected-commit: dc8a365f875da905e3e6070b279f1a41ce9db885

  - name: Generate UI
    runs: make generate-ui

  - uses: go/bump
    with:
      deps: github.com/golang-jwt/jwt/v4@v4.5.1 golang.org/x/crypto@v0.31.0

  - uses: go/build
    with:
      packages: .
      output: alloy
      tags: netgo,builtinassets,promtail_journal_enabled

  - name: Setup default config files
    runs: |
      mkdir -p ${{targets.contextdir}}/etc/alloy/
      install -m644 -D example-config.alloy ${{targets.contextdir}}/etc/alloy/config.alloy

subpackages:
  - name: "${{package.name}}-compat"
    # https://github.com/grafana/alloy/blob/61225a67c0e7bdea2d348c0ce884ed713e5f8740/Dockerfile#L61
    description: "Compatibility package to place binaries in the location expected by upstream Dockerfile"
    pipeline:
      - runs: |
          mkdir -p "${{targets.contextdir}}/bin"
          ln -sf /usr/bin/alloy ${{targets.contextdir}}/bin/alloy

test:
  pipeline:
    - runs: |
        /usr/bin/alloy --version
        alloy --version
        alloy --help

update:
  enabled: true
  ignore-regex-patterns:
    - -rc
  github:
    identifier: grafana/alloy
    strip-prefix: v
    use-tag: true
    tag-filter-prefix: v
