package:
  name: grype
  version: 0.86.0
  epoch: 1
  description: Vulnerability scanner for container images, filesystems, and SBOMs
  copyright:
    - license: Apache-2.0

environment:
  environment:
    CGO_ENABLED: "0"

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/anchore/grype
      tag: v${{package.version}}
      expected-commit: 486b5b3d25f00006c84a13e3dacdc468aeef2ddb

  - uses: go/bump
    with:
      deps: golang.org/x/crypto@v0.31.0

  - uses: go/build
    with:
      ldflags: -X main.version=${{package.version}}
      output: grype
      packages: ./cmd/grype

  - uses: strip

update:
  enabled: true
  github:
    identifier: anchore/grype
    strip-prefix: v

test:
  pipeline:
    - runs: |
        grype --version
        grype --help
