package:
  name: hcloud
  version: 1.49.0
  epoch: 1
  description: A command-line interface for Hetzner Cloud
  copyright:
    - license: MIT

environment:
  contents:
    packages:
      - busybox
      - ca-certificates-bundle
      - go
  environment:
    CGO_ENABLED: "0"

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/hetznercloud/cli
      tag: v${{package.version}}
      expected-commit: fbcbf3b153e2ca14364a3af57ba574dbb1e472ac

  - uses: go/bump
    with:
      deps: golang.org/x/crypto@v0.31.0

  - uses: go/build
    with:
      packages: ./cmd/hcloud/main.go
      ldflags: |
        -s -w
        -X main.version=internal/version.version=${{package.version}}
      output: hcloud

  - uses: strip

update:
  enabled: true
  github:
    identifier: hetznercloud/cli
    strip-prefix: v

test:
  pipeline:
    - runs: |
        hcloud version
        hcloud --help
