package:
  name: htop
  version: 3.3.0
  epoch: 2
  description: "A cross-platform interactive process viewer."
  copyright:
    - license: GPL-2.0-or-later

environment:
  contents:
    packages:
      - autoconf
      - automake
      - build-base
      - busybox
      - libcap-dev
      - libnl3-dev
      - linux-headers
      - ncurses-dev
      - openssf-compiler-options
      - pkgconf-dev

pipeline:
  - uses: fetch
    with:
      uri: https://github.com/htop-dev/htop/releases/download/${{package.version}}/htop-${{package.version}}.tar.xz
      expected-sha256: a69acf9b42ff592c4861010fce7d8006805f0d6ef0e8ee647a6ee6e59b743d5c

  - runs: ./autogen.sh

  - uses: autoconf/configure
    with:
      opts: |
        --prefix="/usr" \
        --sysconfdir="/etc" \
        --mandir="/usr/share/man" \
        --localstatedir="/var" \
        --enable-cgroup \
        --enable-capabilities \
        --enable-delayacct \
        --enable-taskstats

  - uses: autoconf/make

  - uses: autoconf/make-install

  - uses: strip

update:
  enabled: true
  release-monitor:
    identifier: 1332

test:
  pipeline:
    # AUTOGENERATED
    - runs: |
        htop --version
        htop --help
