package:
  name: kapp-controller
  version: 0.54.1
  epoch: 0
  description: Continuous delivery and package management for Kubernetes
  copyright:
    - license: Apache-2.0
  dependencies:
    runtime:
      - age
      - busybox
      - cue
      - git
      - helm
      - kapp
      - kbld
      - openssh-client
      - sops
      - vendir
      - ytt

pipeline:
  - uses: git-checkout
    with:
      expected-commit: c1d08f9df47a68659d0f37065060fb02b0dd32a5
      repository: https://github.com/carvel-dev/kapp-controller
      tag: v${{package.version}}

  - uses: go/bump
    with:
      deps: go.opentelemetry.io/contrib/instrumentation/google.golang.org/grpc/otelgrpc@v0.46.0 go.opentelemetry.io/contrib/instrumentation/net/http/otelhttp@v0.46.0 go.opentelemetry.io/otel/exporters/otlp/otlptrace/otlptracegrpc@v1.21.0

  - uses: go/build
    with:
      packages: ./cmd/controller
      output: kapp-controller
      ldflags: |
        -X main.Version=v${{package.version}}

subpackages:
  - name: ${{package.name}}-compat
    description: "upstream image have executable placed at /"
    pipeline:
      - runs: |
          mkdir -p ${{targets.contextdir}}
          ln -sf /usr/bin/kapp-controller ${{targets.contextdir}}/kapp-controller
          ln -sf /usr/bin/helm ${{targets.contextdir}}/helm
          ln -sf /usr/bin/ytt ${{targets.contextdir}}/ytt
          ln -sf /usr/bin/age ${{targets.contextdir}}/age
          ln -sf /usr/bin/kbld ${{targets.contextdir}}/kbld
          ln -sf /usr/bin/vendir ${{targets.contextdir}}/vendir
          ln -sf /usr/bin/kapp ${{targets.contextdir}}/kapp
          ln -sf /usr/bin/cue ${{targets.contextdir}}/cue
          ln -sf /usr/bin/sops ${{targets.contextdir}}/sops

update:
  enabled: true
  github:
    identifier: carvel-dev/kapp-controller
    strip-prefix: v

test:
  pipeline:
    - name: help message
      runs: |
        kapp-controller --help
