package:
  name: karpenter-1.0
  version: 1.0.8
  epoch: 1
  description: Karpenter is a Kubernetes Node Autoscaler built for flexibility, performance, and simplicity.
  copyright:
    - license: Apache-2.0
  dependencies:
    provides:
      - karpenter=${{package.full-version}}
      - karpenter-provider-aws=${{package.full-version}}

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/aws/karpenter-provider-aws
      tag: v${{package.version}}
      expected-commit: a2875e3f66b4d12b08e0462ee0b027b932f8930d

  - uses: go/bump
    with:
      deps: golang.org/x/net@v0.33.0

  - uses: go/build
    with:
      packages: ./cmd/controller
      output: controller
      ldflags: -X=sigs.k8s.io/karpenter/pkg/operator.Version=${{package.version}}

update:
  enabled: true
  github:
    identifier: aws/karpenter-provider-aws
    tag-filter: v1.0.
    strip-prefix: v

test:
  environment:
    environment:
      # Required for test, otherwise application returns error when running --help.
      SYSTEM_NAMESPACE: default
  pipeline:
    - name: Check application responds to --help command
      runs: controller --help
