package:
  name: kine
  version: 0.13.7
  epoch: 1
  description: Run Kubernetes on MySQL, Postgres, sqlite, dqlite, not etcd.
  copyright:
    - license: Apache-2.0
  dependencies:
    runtime:
      - ca-certificates-bundle

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - git
      - go

pipeline:
  - uses: git-checkout
    with:
      destination: kine
      expected-commit: 872c9d923036556cb9a312ebeb452d55b36d76b3
      repository: https://github.com/k3s-io/kine
      tag: v${{package.version}}

  - uses: go/bump
    with:
      deps: go.opentelemetry.io/otel/sdk@v1.21.0 golang.org/x/net@v0.33.0
      modroot: kine

  - runs: |
      cd kine
      ./scripts/build
      install -Dm755 ./bin/kine "${{targets.destdir}}/usr/bin/kine"

  - uses: strip

update:
  enabled: true
  github:
    identifier: k3s-io/kine
    strip-prefix: v

test:
  environment:
    contents:
      packages:
        - sqlite
        - curl
  pipeline:
    - name: "Check kine version"
      runs: |
        kine --version
        kine --help
    - name: "Test kine with SQLite backend"
      uses: test/daemon-check-output
      with:
        start: |
          kine --endpoint sqlite://kine.db
        timeout: 30
        expected_output: |
          Kine available at http://127.0.0.1:2379
        post: |
          # Wait for kine to start
          sleep 5

          # Check metrics endpoint
          curl -s http://localhost:8080/metrics | grep -q "kine_"
