package:
  name: ksops
  version: 4.3.2
  epoch: 4
  description: Flexible Kustomize Plugin for SOPS Encrypted Resources
  copyright:
    - license: Apache-2.0
  dependencies:
    runtime:
      - kustomize

environment:
  contents:
    packages:
      - busybox
      - ca-certificates-bundle
      - go

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/viaduct-ai/kustomize-sops.git
      tag: v${{package.version}}
      expected-commit: 7f6baaa40b4e419bc3c8523e341090de04f3aa73

  - uses: go/bump
    with:
      deps: google.golang.org/grpc@v1.64.1 golang.org/x/crypto@v0.31.0

  - uses: go/build
    with:
      packages: ksops.go
      output: ksops

  - uses: strip

test:
  pipeline:
    - name: Verify binary presence and permissions
      runs: |
        test -f /usr/bin/ksops
        test -x /usr/bin/ksops
    - name: Basic plugin test
      runs: |
        # Setup test directory
        mkdir -p ~/.config/kustomize/plugin/viaduct.ai/v1/ksops/
        cp /usr/bin/ksops ~/.config/kustomize/plugin/viaduct.ai/v1/ksops/

        # Create a test kustomization that references the plugin
        cat > kustomization.yaml <<EOF
        apiVersion: kustomize.config.k8s.io/v1beta1
        kind: Kustomization
        resources:
        - resource.yaml
        EOF

        # Create a test resource
        cat > resource.yaml <<EOF
        apiVersion: v1
        kind: ConfigMap
        metadata:
          name: test-config
        data:
          key: value
        EOF

        # Test if kustomize can find and recognize the plugin
        kustomize build . | grep -q "test-config" || { echo "Failed to find test resource in output"; exit 1; }

update:
  enabled: true
  github:
    identifier: viaduct-ai/kustomize-sops
    strip-prefix: v
