package:
  name: kubeadm-controlplane-controller
  version: 1.9.3
  epoch: 0
  description: Cluster API kubeadm controlplane controller
  copyright:
    - license: Apache-2.0

environment:
  contents:
    packages:
      - busybox
      - ca-certificates-bundle
      - go
  environment:
    CGO_ENABLED: "0"

pipeline:
  - uses: git-checkout
    with:
      expected-commit: cd279dd0c24c5472db45255e3805ae16c61e1432
      repository: https://github.com/kubernetes-sigs/cluster-api
      tag: v${{package.version}}

  - uses: go/build
    with:
      ldflags: -s -w
      output: kubeadm-controlplane-controller
      packages: ./controlplane/kubeadm

  - uses: strip

update:
  enabled: true
  github:
    identifier: kubernetes-sigs/cluster-api
    strip-prefix: v
    tag-filter: v
    use-tag: true

test:
  pipeline:
    - runs: |
        OUTPUT=$(kubeadm-controlplane-controller --help 2>&1 || true)

        # Display the output
        echo "$OUTPUT"

        # Check if the output contains the expected help message
        if echo "$OUTPUT" | grep -q "Usage of kubeadm-controlplane-controller:"; then
            echo "Help flag output detected as expected."
        else
            echo "Help flag did not produce the expected output."
            exit 1
        fi
