package:
  name: kube-vip
  version: 0.8.7
  epoch: 1
  description: Kubernetes Control Plane Virtual IP and Load-Balancer
  copyright:
    - license: Apache-2.0

environment:
  environment:
    CGO_ENABLED: "0"

pipeline:
  - uses: git-checkout
    with:
      expected-commit: 4c70d873816b4405ff830e0e5eac39f8d5c548d4
      repository: https://github.com/kube-vip/kube-vip
      tag: v${{package.version}}

  - uses: go/bump
    with:
      deps: golang.org/x/crypto@v0.31.0

  - uses: go/build
    with:
      ldflags: -s -w -X=main.Version=${{package.version}} -X=main.Build=$(git rev-parse HEAD) -extldflags -static
      output: kube-vip
      packages: .

  - uses: strip

subpackages:
  - name: "${{package.name}}-compat"
    # https://github.com/kube-vip/kube-vip/blob/2872256a89a1e39b62c9518728ec22e2f33af4eb/Dockerfile#L19
    description: "Compatibility package to place binaries in the location expected by upstream Dockerfile"
    pipeline:
      - runs: |
          mkdir -p "${{targets.subpkgdir}}"
          ln -sf /usr/bin/kube-vip ${{targets.subpkgdir}}/kube-vip

update:
  enabled: true
  github:
    identifier: kube-vip/kube-vip
    strip-prefix: v

test:
  environment:
    contents:
      packages:
        - ${{package.name}}-compat
  pipeline:
    - runs: |
        kube-vip -h
        /kube-vip -h
        kube-vip version
        kube-vip --help
