package:
  name: kyverno-policy-reporter
  version: 2.24.2
  epoch: 1
  description: Monitoring and Observability Tool for the PolicyReport CRD with an optional UI.
  copyright:
    - license: Apache-2.0

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - go

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/kyverno/policy-reporter
      tag: policy-reporter-${{package.version}}
      expected-commit: de07f8e4d61f65c42cd999db8141cff5fda65d48

  - uses: go/bump
    with:
      deps: golang.org/x/crypto@v0.31.0

  - uses: go/build
    with:
      packages: .
      output: policyreporter
      ldflags: -w -linkmode external -extldflags "-static"
      tags: sqlite_unlock_notify

  - runs: |
      mkdir -p ${{targets.destdir}}/app/templates
      cp -R ./templates ${{targets.destdir}}/app/templates

  - uses: strip

subpackages:
  - name: kyverno-policy-reporter-compat
    description: compatibility symlinks package for policyreporter Dockerfile
    pipeline:
      - runs: |
          # Symlink the binary from usr/bin to /app/
          mkdir -p ${{targets.subpkgdir}}/app
          ln -sf /usr/bin/policyreporter ${{targets.subpkgdir}}/app/policyreporter

update:
  enabled: true
  ignore-regex-patterns:
    - "-RC*"
    - "dev"
    - "-chart-" # Avoid Helm chart tags
    - "preview"
  git:
    strip-prefix: policy-reporter-
    tag-filter-prefix: policy-reporter

test:
  pipeline:
    # AUTOGENERATED
    - runs: |
        policyreporter --help
        policyreporter version
