package:
  name: libffi
  version: 3.4.6
  epoch: 5
  description: "portable foreign function interface library"
  copyright:
    - license: MIT

environment:
  contents:
    packages:
      - autoconf
      - automake
      - build-base
      - busybox
      - ca-certificates-bundle
      - libtool
      - openssf-compiler-options
      - texinfo

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/libffi/libffi.git
      tag: v${{package.version}}
      expected-commit: 3d0ce1e6fcf19f853894862abcbac0ae78a7be60

  - uses: autoconf/configure
    with:
      opts: >
        --disable-builddir --enable-portable-binary --enable-pax_emutramp --disable-exec-static-tramp


  - uses: autoconf/make

  - uses: autoconf/make-install

  - uses: strip

subpackages:
  - name: "libffi-dev"
    description: "libffi headers"
    pipeline:
      - uses: split/dev
    dependencies:
      runtime:
        - libffi
    test:
      environment:
        contents:
          packages:
            - build-base
      pipeline:
        - name: Basic closure test
          runs: |
            echo '#include <stdio.h>' > test_closure.c
            echo '#include <ffi.h>' >> test_closure.c
            echo 'void puts_binding(ffi_cif *cif, unsigned int *ret, void* args[], FILE *stream) { *ret = fputs(*(char **)args[0], stream); }' >> test_closure.c
            echo 'int main() { ffi_cif cif; ffi_type *args[1]; ffi_closure *closure; int (*bound_puts)(char *); int rc; closure = ffi_closure_alloc(sizeof(ffi_closure), &bound_puts); if (closure) { args[0] = &ffi_type_pointer; if (ffi_prep_cif(&cif, FFI_DEFAULT_ABI, 1, &ffi_type_uint, args) == FFI_OK) { if (ffi_prep_closure_loc(closure, &cif, puts_binding, stdout, bound_puts) == FFI_OK) { rc = bound_puts("Hello World!"); } } ffi_closure_free(closure); } return 0; }' >> test_closure.c
            gcc -Wno-incompatible-pointer-types -o test_closure test_closure.c -lffi
            ./test_closure | grep -q Hello\ World || exit 1
        - uses: test/pkgconf

  - name: "libffi-doc"
    description: "libffi docs"
    pipeline:
      - uses: split/manpages
      - uses: split/infodir

update:
  enabled: true
  github:
    identifier: libffi/libffi
    strip-prefix: v

test:
  pipeline:
    - uses: test/ldd-check
      with:
        files: |-
          /usr/lib64/libffi.so
          /usr/lib64/libffi.so.8
          /usr/lib64/libffi.so.8.1.4
