package:
  name: libuv
  version: 1.49.2
  epoch: 0
  description: "cross-platform asynchronous I/O library"
  copyright:
    - license: MIT AND ISC

environment:
  contents:
    packages:
      - autoconf
      - build-base
      - busybox
      - ca-certificates-bundle
      - libtool
      - openssf-compiler-options
      - wolfi-base

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/libuv/libuv.git
      tag: v${{package.version}}
      expected-commit: e1095c7a4373ce00cd8874d8e820de5afb25776e

  - runs: ./autogen.sh

  - uses: autoconf/configure

  - uses: autoconf/make

  - uses: autoconf/make-install

  - uses: strip

subpackages:
  - name: "libuv-dev"
    description: "libuv development headers"
    pipeline:
      - uses: split/dev
    dependencies:
      runtime:
        - libuv
    test:
      pipeline:
        - uses: test/pkgconf

update:
  enabled: true
  github:
    identifier: libuv/libuv
    strip-prefix: v

test:
  environment:
    contents:
      packages:
        - libuv-dev
        - build-base
        - gcc
        - make
  pipeline:
    - name: "Check libuv Installation"
      runs: |
        find /usr /usr/local -name 'libuv.so' || (echo "libuv library not found!" && exit 1)
    - name: "Compile and Run libuv Test Program"
      runs: |
        # Test program to check if libuv headers and functionality are working
        cat <<EOF > test_libuv.c
        #include <stdio.h>
        #include <uv.h>

        int main() {
            uv_loop_t *loop = uv_default_loop();
            printf("Now quitting.\n");
            uv_run(loop, UV_RUN_DEFAULT);
            return 0;
        }
        EOF

        gcc test_libuv.c -o test_libuv -luv || (echo "libuv test compilation failed!" && exit 1)
        ./test_libuv || (echo "libuv test failed!" && exit 1)
    - uses: test/ldd-check
      with:
        files: |-
          /usr/lib/libuv.so.1
          /usr/lib/libuv.so.1.0.0
