package:
  name: malcontent
  version: 1.6.0
  epoch: 0
  description: enumerate file capabilities, including malicious behaviors
  copyright:
    - license: Apache-2.0
  dependencies:
    runtime:
      - ca-certificates-bundle
      - yara

environment:
  contents:
    packages:
      - openssf-compiler-options
      - openssl-dev
      - yara-dev

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/chainguard-dev/malcontent
      tag: v${{package.version}}
      expected-commit: 74e0b0dce681f640eaf45e72f4291a99a7310d9f

  - uses: go/build
    with:
      packages: ./cmd/mal
      ldflags: -s -w
      output: mal

  - uses: strip

test:
  environment:
    contents:
      packages:
        - openssl
        - crane
  pipeline:
    - name: Verify malcontent version
      runs: |
        set -o pipefail
        output=$(mal --version)
        test "$output" == "malcontent version v${{package.version}}"
        mal --version
        mal --help
    - name: Verify malcontent on yara
      runs: |
        set -o pipefail
        mal analyze /usr/bin/yara | grep LOW
    - name: Verify malcontent on openssl
      runs: |
        set -o pipefail
        mal analyze /usr/bin/openssl | grep MED
    - name: Verify malcontent on crane
      runs: |
        set -o pipefail
        mal analyze /usr/bin/crane | grep MED
    - name: Verify malcontent diff
      runs: |
        set -o pipefail
        mal diff /usr/bin/openssl /usr/bin/crane | grep "archives/zip"

update:
  enabled: true
  github:
    identifier: chainguard-dev/malcontent
    strip-prefix: v
