package:
  name: minio-operator
  version: 6.0.4
  epoch: 3
  description: Minio Operator creates/configures/manages Minio on Kubernetes
  copyright:
    - license: AGPL-3.0-only

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/minio/operator
      tag: v${{package.version}}
      expected-commit: c5b838c475609921935bd4f335fdbc4b6846be14

  - uses: go/bump
    with:
      deps: github.com/golang-jwt/jwt/v4@v4.5.1 golang.org/x/crypto@v0.31.0

  - uses: go/build
    with:
      modroot: ./cmd/operator
      packages: .
      output: minio-operator
      ldflags: -w -X github.com/minio/operator/pkg.ReleaseTag=${{package.full-version}} -X github.com/minio/operator/pkg.Version=${{package.full-version}} -X github.com/minio/operator/pkg.ShortCommitID=$(git rev-parse HEAD)

  - runs: |
      mkdir ${{targets.destdir}}/licenses
      cp CREDITS LICENSE ${{targets.destdir}}/licenses/

subpackages:
  - name: ${{package.name}}-sidecar
    description: sidecar for minio-operator
    pipeline:
      - uses: go/bump
        working-directory: ./sidecar
        with:
          deps: github.com/golang-jwt/jwt/v4@v4.5.1
      - uses: go/build
        working-directory: ./sidecar
        with:
          modroot: ./cmd/sidecar
          packages: .
          output: minio-operator-sidecar
          ldflags: -w -X github.com/minio/operator/sidecar/pkg.ReleaseTag=${{package.full-version}} -X github.com/minio/operator/sidecar/pkg.Version=${{package.full-version}} -X github.com/minio/operator/sidecar/pkg.ShortCommitID=$(git rev-parse HEAD)
      - runs: |
          mkdir ${{targets.contextdir}}/licenses
          cp CREDITS LICENSE ${{targets.contextdir}}/licenses/

  - name: ${{package.name}}-sidecar-compat
    description: compatibility symlinks package for minio-operator-sidecar Dockerfile
    pipeline:
      - runs: |
          mkdir -p ${{targets.contextdir}}/
          ln -sf /usr/bin/minio-operator-sidecar ${{targets.contextdir}}/minio-operator-sidecar

  - name: ${{package.name}}-compat
    description: compatibility symlinks package for minio-operator Dockerfile
    pipeline:
      - runs: |
          mkdir -p ${{targets.contextdir}}/
          ln -sf /usr/bin/minio-operator ${{targets.contextdir}}/minio-operator

update:
  enabled: true
  github:
    identifier: minio/operator
    strip-prefix: v

# comprehensive test with kwok and minio's kustomize want ephemeral storage, so just check version here
test:
  pipeline:
    - runs: |
        minio-operator --version
        minio-operator --help
