package:
  name: nats-server
  version: 2.10.23
  epoch: 1
  description: High-Performance server for NATS.io, the cloud and edge native messaging system.
  copyright:
    - license: Apache-2.0

environment:
  contents:
    packages:
      - busybox
      - ca-certificates-bundle
      - go
      - openssf-compiler-options
      - wolfi-baselayout

pipeline:
  # We can't use go/install because this requires a specific go version
  - uses: git-checkout
    with:
      repository: https://github.com/nats-io/nats-server
      tag: v${{package.version}}
      expected-commit: 145e44d6e68132856b18f1576f67b8eb27e980f9

  - uses: go/bump
    with:
      deps: golang.org/x/crypto@v0.31.0

  - runs: |
      mkdir -p ${{targets.destdir}}/usr/bin
      mkdir -p ${{targets.destdir}}/etc/nats
      go build \
        -ldflags "-w -X github.com/nats-io/nats-server/v2/server.gitCommit=$(git rev-parse HEAD)" \
        -o ${{targets.destdir}}/usr/bin/nats-server \
        .
      mv docker/nats-server.conf ${{targets.destdir}}/etc/nats/nats-server.conf

  - uses: strip

update:
  enabled: true
  github:
    identifier: nats-io/nats-server
    strip-prefix: v

test:
  environment:
    contents:
      packages:
        - bash
        - curl
        - jq
        - nats
  pipeline:
    - name: "Test NATS server startup and interaction"
      uses: test/daemon-check-output
      with:
        start: nats-server -DV
        timeout: 30
        expected_output: |
          Server is ready
        post: |
          #!/bin/sh -e
          # Test basic pub/sub functionality with running server
          nats pub test.subject "test message" --server nats://localhost:4222 &
          nats sub test.subject --count 1 --server nats://localhost:4222 &
          # Verify server monitoring endpoint
          curl -s http://localhost:8222/varz | jq .server_id
    - name: "Test monitoring server startup"
      uses: test/daemon-check-output
      with:
        start: nats-server -m 8222
        timeout: 15
        expected_output: |
          Server is ready
        post: |
          #!/bin/sh -e
          # Verify monitoring endpoints
          curl -s http://localhost:8222/varz | jq .server_id
          curl -s http://localhost:8222/connz | jq .now
          curl -s http://localhost:8222/routez | jq .now
