package:
  name: newrelic-nri-kube-events
  version: 2.11.4
  epoch: 0
  description: New Relic integration that forwards Kubernetes events to New Relic
  copyright:
    - license: Apache-2.0

environment:
  contents:
    packages:
      - busybox
      - ca-certificates-bundle
      - openssf-compiler-options
      - wolfi-baselayout

pipeline:
  # We can't use go/install because this requires specific ldflags to set the version
  - uses: git-checkout
    with:
      repository: https://github.com/newrelic/nri-kube-events
      tag: v${{package.version}}
      expected-commit: 816e48963eeff5e268722c57a220bbe14d6a2795

  - uses: go/bump
    with:
      deps: golang.org/x/net@v0.33.0

  - uses: go/build
    with:
      packages: ./cmd/nri-kube-events
      ldflags: -X main.integrationVersion=v${{ package.version }}
      output: nri-kube-events

update:
  enabled: true
  github:
    identifier: newrelic/nri-kube-events
    strip-prefix: v
    tag-filter: v

test:
  pipeline:
    # AUTOGENERATED
    - runs: |
        nri-kube-events --help
