package:
  name: nvidia-container-toolkit
  version: 1.17.3
  epoch: 0
  description: Build and run containers leveraging NVIDIA GPUs
  copyright:
    - license: Apache-2.0
  dependencies:
    runtime:
      - libnvidia-container

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - go
      - openssf-compiler-options
  environment:
    GCC_SPEC_FILE: /dev/null

pipeline:
  - uses: git-checkout
    with:
      expected-commit: cb82e29c75d387992bf59eb6eadf5d96cb6d4747
      repository: https://github.com/NVIDIA/nvidia-container-toolkit
      tag: v${{package.version}}

data:
  - name: commands
    items:
      nvidia-container-runtime-hook: nvidia-container-runtime-hook
      nvidia-container-runtime-cdi: nvidia-container-runtime.cdi
      nvidia-container-runtime-legacy: nvidia-container-runtime.legacy
      nvidia-container-runtime: nvidia-container-runtime
      nvidia-cdi-hook: nvidia-cdi-hook
      nvidia-ctk: nvidia-ctk

  - name: tools
    items:
      containerd: containerd
      crio: crio
      docker: docker
      nvidia-toolkit: nvidia-toolkit
      operator: operator
      toolkit: toolkit

subpackages:
  - range: commands
    name: "${{package.name}}-${{range.key}}"
    pipeline:
      - uses: go/build
        with:
          modroot: .
          packages: ./cmd/${{range.value}}
          ldflags: -s -w '-extldflags=-Wl,-undefined,dynamic_lookup' -X github.com/NVIDIA/nvidia-container-toolkit/internal/info.gitCommit=$(git rev-parse HEAD) -X github.com/NVIDIA/nvidia-container-toolkit/internal/info.version=${{package.version}}
          output: ${{range.value}}
          vendor: true
    test:
      pipeline:
        - runs: |
            apk add runc # runc is just a placeholder, the actual runtime binary is TBD by the user
            ${{range.value}} --help

  - range: tools
    name: "${{package.name}}-${{range.key}}"
    pipeline:
      - uses: go/build
        with:
          modroot: .
          packages: ./tools/container/${{range.key}}
          ldflags: -s -w -X main.Version=${{package.version}}
          output: ${{range.key}}
          vendor: true
      - runs: |
          # Ref: https://github.com/NVIDIA/nvidia-container-toolkit/blob/v1.15.0/deployments/container/Dockerfile.ubi8#L74
          mkdir -p ${{targets.contextdir}}/work
          ln -sf /usr/bin/${{range.key}} ${{targets.contextdir}}/work/${{range.key}}
    test:
      pipeline:
        - runs: |
            # Operator requires root privileges to run
            if [ "${{range.key}}" = "operator" ]; then
              set +e
              /work/${{range.key}} 2>&1 | grep -q "Permission denied"
              exit $?
            fi
            /work/${{range.key}} --version

update:
  enabled: true
  ignore-regex-patterns:
    - -rc
  github:
    identifier: NVIDIA/nvidia-container-toolkit
    strip-prefix: v
