package:
  name: opentofu-1.8
  version: 1.8.7
  epoch: 1
  copyright:
    - license: MPL-2.0
  dependencies:
    provides:
      - opentofu=${{package.full-version}}

environment:
  environment:
    CGO_ENABLED: 0

pipeline:
  - uses: git-checkout
    with:
      expected-commit: 82fdce1c7de0005449fe5848d134757c5801e67d
      repository: https://github.com/opentofu/opentofu
      tag: v${{package.version}}

  - uses: go/bump
    with:
      deps: golang.org/x/crypto@v0.31.0
      modroot: .

  - uses: go/build
    with:
      ldflags: -s -w -X 'github.com/opentofu/opentofu/version.dev=no'
      modroot: .
      output: tofu
      packages: ./cmd/tofu

  - uses: strip

subpackages:
  - name: ${{package.name}}-compat
    description: Compat package for opentofu
    dependencies:
      provides:
        - opentofu-compat=${{package.full-version}}
    pipeline:
      - runs: |
          mkdir -p "${{targets.subpkgdir}}"/usr/local/bin
          ln -s /usr/bin/opentofu "${{targets.subpkgdir}}"/usr/local/bin

  - name: ${{package.name}}-local-provider-config
    description: Configure opentofu to use local providers
    dependencies:
      provides:
        - opentofu-local-provider-config=${{package.full-version}}
    pipeline:
      - runs: |
          mkdir -p "${{targets.subpkgdir}}"/opentofu/provider-mirror
          cat > "${{targets.subpkgdir}}"/opentofu/.opentofurc <<EOF
          provider_installation {
            filesystem_mirror {
              path    = "/opentofu/provider-mirror"
              include = ["*/*"]
            }
            direct {
              exclude = ["*/*"]
            }
          }
          EOF

update:
  enabled: true
  ignore-regex-patterns:
    - 'rc'
    - 'beta'
  github:
    identifier: opentofu/opentofu
    strip-prefix: v
    use-tag: true
    tag-filter-prefix: v1.8

test:
  pipeline:
    # AUTOGENERATED
    - runs: |
        tofu --version
        tofu --help
