package:
  name: openssh
  version: 9.9_p1
  epoch: 3
  description: "the OpenBSD SSH implementation"
  copyright:
    - license: ISC
  dependencies:
    runtime:
      - openssh-client
      - openssh-server
      - openssh-sftp-server

environment:
  contents:
    packages:
      - bash
      - build-base
      - busybox
      - ca-certificates-bundle
      - libedit-dev
      - openssf-compiler-options
      - openssl-dev
      - wolfi-baselayout
      - zlib-dev

var-transforms:
  - from: ${{package.version}}
    match: \_(p\d+)$
    replace: $1
    to: mangled-package-version

pipeline:
  - uses: fetch
    with:
      uri: https://ftp.openbsd.org/pub/OpenBSD/OpenSSH/portable/openssh-${{vars.mangled-package-version}}.tar.gz
      expected-sha256: b343fbcdbff87f15b1986e6e15d6d4fc9a7d36066be6b7fb507087ba8f966c02

  - name: Configure
    runs: |
      ./configure \
         --host=${{host.triplet.gnu}} \
         --target=${{host.triplet.gnu}} \
         --prefix=/usr \
         --datadir=/usr/share \
         --sysconfdir=/etc/ssh \
         --libexecdir=/usr/lib/ssh \
         --with-pid-dir=/run \
         --with-mantype=doc \
         --disable-utmp \
         --disable-wtmp \
         --disable-lastlog \
         --disable-strip \
         --with-privsep-path=/var/empty \
         --with-xauth=/usr/bin/xauth \
         --with-default-path='/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin' \
         --with-privsep-user=sshd \
         --with-ssl-engine \
         --with-libedit

  - uses: autoconf/make

  - uses: autoconf/make-install

  - uses: strip

subpackages:
  - name: "openssh-doc"
    description: "OpenSSH documentation"
    pipeline:
      - uses: split/manpages

  - name: "openssh-keygen"
    description: "OpenSSH key generator"
    pipeline:
      - runs: |
          mkdir -p "${{targets.subpkgdir}}"/usr/bin
          mv "${{targets.destdir}}"/usr/bin/ssh-keygen "${{targets.subpkgdir}}"/usr/bin/

  - name: "openssh-keyscan"
    description: "OpenSSH key scanner"
    pipeline:
      - runs: |
          mkdir -p "${{targets.subpkgdir}}"/usr/bin
          mv "${{targets.destdir}}"/usr/bin/ssh-keyscan "${{targets.subpkgdir}}"/usr/bin/

  - name: "openssh-keysign"
    description: "OpenSSH key signing tool"
    pipeline:
      - runs: |
          mkdir -p "${{targets.subpkgdir}}"/usr/lib/ssh
          mv "${{targets.destdir}}"/usr/lib/ssh/ssh-keysign "${{targets.subpkgdir}}"/usr/lib/ssh/

  - name: "openssh-sftp-server"
    description: "OpenSSH SFTP server"
    pipeline:
      - runs: |
          mkdir -p "${{targets.subpkgdir}}"/usr/lib/ssh
          mv "${{targets.destdir}}"/usr/lib/ssh/sftp-server "${{targets.subpkgdir}}"/usr/lib/ssh/

  - name: "openssh-pkcs11-helper"
    description: "PKCS11 helper for OpenSSH"
    pipeline:
      - runs: |
          mkdir -p "${{targets.subpkgdir}}"/usr/lib/ssh
          mv "${{targets.destdir}}"/usr/lib/ssh/ssh-pkcs11-helper "${{targets.subpkgdir}}"/usr/lib/ssh/

  - name: "openssh-sk-helper"
    description: "Security key helper for OpenSSH"
    pipeline:
      - runs: |
          mkdir -p "${{targets.subpkgdir}}"/usr/lib/ssh
          mv "${{targets.destdir}}"/usr/lib/ssh/ssh-sk-helper "${{targets.subpkgdir}}"/usr/lib/ssh/

  - name: "openssh-client"
    description: "OpenSSH client"
    pipeline:
      - runs: |
          mkdir -p "${{targets.subpkgdir}}"/usr
          mv "${{targets.destdir}}"/usr/bin "${{targets.subpkgdir}}"/usr/

          mkdir -p "${{targets.subpkgdir}}"/etc/ssh
          mv "${{targets.destdir}}"/etc/ssh/moduli "${{targets.subpkgdir}}"/etc/ssh/
          mv "${{targets.destdir}}"/etc/ssh/ssh_config "${{targets.subpkgdir}}"/etc/ssh/
          mkdir -p "${{targets.subpkgdir}}"/etc/ssh/ssh_config.d
          sed -i 's|\(^# Host\)|Include /etc/ssh/ssh_config.d/*.conf\n\n\1|' "${{targets.subpkgdir}}"/etc/ssh/ssh_config

  - name: "openssh-server"
    description: "OpenSSH server"
    pipeline:
      - runs: |
          mkdir -p "${{targets.subpkgdir}}"/usr/sbin
          mv "${{targets.destdir}}"/usr/sbin/sshd "${{targets.subpkgdir}}"/usr/sbin/
          mkdir -p "${{targets.subpkgdir}}"/usr/lib/ssh
          mv "${{targets.destdir}}"/usr/lib/ssh/sshd-session "${{targets.subpkgdir}}"/usr/lib/ssh/
    dependencies:
      runtime:
        - openssh-keygen
        - openssh-server-config
    scriptlets:
      post-install: |
        #!/bin/sh
        ssh-keygen -A -q -N ""
    test:
      pipeline:
        - runs: |
            ssh-keygen -A -q -N ""    # This is unfortunate, but scriplets don't run in test environments, so force this here
            /usr/sbin/sshd

  - name: "openssh-service"
    description: "System OpenSSH server unit"
    pipeline:
      - runs: |
          mkdir -p "${{targets.subpkgdir}}"/usr/lib/systemd/system
          install -Dm644  sshd.service "${{targets.subpkgdir}}"/usr/lib/systemd/system
    dependencies:
      runtime:
        - systemd
        - openssh-server

  - name: "openssh-server-config"
    description: "OpenSSH server configuration"
    pipeline:
      - runs: |
          mkdir -p "${{targets.subpkgdir}}"/etc
          mv "${{targets.destdir}}"/etc/ssh "${{targets.subpkgdir}}"/etc/

update:
  enabled: true
  release-monitor:
    identifier: 2565

test:
  pipeline:
    - runs: |
        ssh-keygen -A -q -N ""    # This is unfortunate, but scriplets don't run in test environments, so force this here
        /usr/sbin/sshd
