package:
  name: perl-mozilla-ca
  version: "20240924"
  epoch: 0
  description: Mozilla's CA cert bundle in PEM format
  copyright:
    - license: MPL-2.0

environment:
  contents:
    packages:
      - autoconf
      - automake
      - build-base
      - ca-certificates-bundle
      - openssf-compiler-options
      - perl

pipeline:
  - uses: fetch
    with:
      expected-sha256: c4b1412bbc37dff8cf29af6f92cb47defbe90eebcbc29e407a98638f7a31bcd0
      uri: https://cpan.metacpan.org/authors/id/L/LW/LWP/Mozilla-CA-${{package.version}}.tar.gz

  - uses: perl/make

  - uses: autoconf/make

  - uses: autoconf/make-install

  - uses: perl/cleanup

  - uses: strip

subpackages:
  - name: perl-mozilla-ca-doc
    pipeline:
      - uses: split/manpages
    description: perl-mozilla-ca manpages

test:
  environment:
    contents:
      packages:
        - perl
  pipeline:
    - name: Test
      runs: |
        cat <<EOF > mozilla-ca.pl
        use strict;
        use warnings;

        eval {
            require Mozilla::CA;
            Mozilla::CA->import();
        };
        if (\$@) {
            print "Failed to load Mozilla::CA\n";
            exit 1;
        }
        EOF

        perl mozilla-ca.pl

update:
  enabled: true
  release-monitor:
    identifier: 3136
