package:
  name: portieris
  version: 0.13.22
  epoch: 2
  description: A Kubernetes Admission Controller for verifying image trust.
  copyright:
    - license: Apache-2.0

environment:
  environment:
    CGO_ENABLED: "0"

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/IBM/portieris.git
      tag: v${{package.version}}
      expected-commit: ad0725d34f9ee1aa18078ab2ba624dee26dafba9

  - uses: go/bump
    with:
      deps: golang.org/x/crypto@v0.31.0 golang.org/x/net@v0.33.0

  - uses: go/build
    with:
      packages: "./cmd/portieris"
      ldflags: "-X github.com/IBM/portieris/internal/info.Version=v${{package.version}}"
      tags: containers_image_openpgp
      output: portieris

subpackages:
  - name: portieris-compat
    description: Compat package for portieris
    pipeline:
      - runs: |
          mkdir -p ${{targets.subpkgdir}}/
          ln -s /usr/bin/portieris "${{targets.subpkgdir}}"/portieris

update:
  enabled: true
  github:
    identifier: IBM/portieris
    strip-prefix: v

test:
  pipeline:
    - runs: |
        which portieris
        portieris --help
