package:
  name: prometheus-postgres-exporter
  version: 0.16.0
  epoch: 2
  description: Prometheus Exporter for Postgres server metrics
  copyright:
    - license: Apache-2.0

environment:
  contents:
    packages:
      - bash
      - build-base
      - busybox
      - ca-certificates-bundle
      - curl
      - go

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/prometheus-community/postgres_exporter
      tag: v${{package.version}}
      expected-commit: a324fe37bca5193a293118b940b3df7ab3a8505c

  - uses: go/bump
    with:
      deps: golang.org/x/crypto@v0.31.0 golang.org/x/net@v0.33.0

  - runs: |
      make build

  - runs: |
      install -Dm755 postgres_exporter "${{targets.destdir}}"/usr/bin/postgres_exporter

  - uses: strip

subpackages:
  - name: prometheus-postgres-exporter-bitnami-compat
    pipeline:
      - uses: bitnami/compat
        with:
          image: postgres-exporter
          version-path: 0/debian-12
      - runs: |
          mkdir -p ${{targets.subpkgdir}}/opt/bitnami/postgres-exporter
          ln -s /usr/bin/postgres_exporter ${{targets.subpkgdir}}/opt/bitnami/postgres-exporter/postgres_exporter
    test:
      pipeline:
        - runs: |
            run-script --version
            run-script --help

update:
  enabled: true
  github:
    identifier: prometheus-community/postgres_exporter
    strip-prefix: v

test:
  pipeline:
    # AUTOGENERATED
    - runs: |
        postgres_exporter --version
        postgres_exporter --help
