package:
  name: prometheus-node-exporter
  version: 1.8.2
  epoch: 3
  description: Prometheus Exporter for machine metrics
  copyright:
    - license: Apache-2.0

environment:
  contents:
    packages:
      - bash
      - build-base
      - busybox
      - ca-certificates-bundle
      - curl
      - go

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/prometheus/node_exporter
      tag: v${{package.version}}
      expected-commit: f1e0e8360aa60b6cb5e5cc1560bed348fc2c1895

  - uses: go/bump
    with:
      deps: golang.org/x/crypto@v0.31.0

  - runs: |
      sed -i '/_ "net\/http\/pprof"/d' node_exporter.go
      git diff

  - runs: |
      make build

  - runs: |
      install -Dm755 node_exporter "${{targets.destdir}}"/usr/bin/node_exporter

  - uses: strip

subpackages:
  - name: "prometheus-node-exporter-compat"
    description: "Compatibility package to place binaries in the location expected by upstream helm charts"
    pipeline:
      - runs: |
          # The helm chart expects the node_exporter binaries to be in /bin instead of /usr/bin
          mkdir -p "${{targets.subpkgdir}}"/bin
          ln -sf /usr/bin/node_exporter ${{targets.subpkgdir}}/bin/node_exporter
      - uses: strip

update:
  enabled: true
  github:
    identifier: prometheus/node_exporter
    strip-prefix: v

test:
  pipeline:
    # AUTOGENERATED
    - runs: |
        node_exporter --version
        node_exporter --help
