package:
  name: pulumi-language-yaml
  version: 1.12.0
  epoch: 1
  description: Pulumi Language SDK for YAML
  copyright:
    - license: Apache-2.0

environment:
  contents:
    packages:
      - busybox
      - ca-certificates-bundle
      - git
      - go

pipeline:
  - uses: git-checkout
    with:
      destination: ${{package.name}}
      expected-commit: 7d95c7f6ffb736538faa86e8f6319e24df57e5cb
      repository: https://github.com/pulumi/pulumi-yaml.git
      tag: v${{package.version}}

  - uses: go/bump
    with:
      deps: golang.org/x/crypto@v0.31.0
      modroot: pulumi-language-yaml

  - pipeline:
      - runs: |
          set -x

          export CGO_ENABLED=0 GO111MODULE=on
          go build \
            -o "${{targets.destdir}}/usr/bin/pulumi-language-yaml" \
            -ldflags="-s -w -X github.com/pulumi/pulumi-yaml/pkg/version.Version=v${{package.version}}" \
            ./cmd/pulumi-language-yaml/
      - uses: strip
    working-directory: ${{package.name}}

update:
  enabled: true
  github:
    identifier: pulumi/pulumi-yaml
    strip-prefix: v

test:
  pipeline:
    # AUTOGENERATED
    - runs: |
        pulumi-language-yaml --help
