package:
  name: py3-requests-unixsocket
  version: 0.3.0
  epoch: 1
  description: Use requests to talk HTTP via a UNIX domain socket
  copyright:
    - license: Apache-2.0
  dependencies:
    provider-priority: 0

environment:
  contents:
    packages:
      - build-base
      - busybox
      - py3-supported-pip
      - py3-supported-python
      - py3-supported-setuptools
      - py3-supported-wheel

vars:
  pypi-package: requests-unixsocket
  module-name: requests_unixsocket

data:
  - name: py-versions
    items:
      3.10: '310'
      3.11: '311'
      3.12: '312'
      3.13: '313'

pipeline:
  - uses: fetch
    with:
      expected-sha256: 28304283ea9357d45fff58ad5b11e47708cfbf5806817aa59b2a363228ee971e
      uri: https://files.pythonhosted.org/packages/source/r/requests-unixsocket/requests-unixsocket-${{package.version}}.tar.gz

subpackages:
  - range: py-versions
    name: py${{range.key}}-${{vars.pypi-package}}
    description: ${{vars.pypi-package}} installed for python${{range.key}}
    dependencies:
      runtime:
        - py${{range.key}}-requests
      provides:
        - py3-${{vars.pypi-package}}
      provider-priority: ${{range.value}}
    pipeline:
      - uses: py/pip-build-install
        with:
          python: python${{range.key}}
      - uses: strip
    test:
      pipeline:
        - uses: python/import
          with:
            python: python${{range.key}}
            import: ${{vars.module-name}}

update:
  enabled: true
  release-monitor:
    identifier: 375444
