package:
  name: py3-jiter
  version: 0.8.2
  epoch: 1
  description: Fast iterable JSON parser
  copyright:
    - license: MIT
  dependencies:
    provider-priority: 0

vars:
  pypi-package: jiter

data:
  - name: py-versions
    items:
      3.10: '310'
      3.11: '311'
      3.12: '312'
      3.13: '313'

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - maturin
      - openssf-compiler-options
      - py3-supported-maturin
      - py3-supported-orjson
      - py3-supported-pip
      - py3-supported-ujson
      - wolfi-base

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/pydantic/jiter.git
      tag: v${{package.version}}
      expected-commit: 5f208ea1feccc9d5dc7c0f18eab443a4e0400e13

subpackages:
  - range: py-versions
    name: py${{range.key}}-${{vars.pypi-package}}
    description: ${{vars.pypi-package}} installed for python${{range.key}}
    dependencies:
      provides:
        - py3-${{vars.pypi-package}}
      provider-priority: ${{range.value}}
    pipeline:
      - uses: py/pip-build-install
        working-directory: /home/build/crates/jiter-python
        with:
          python: python${{range.key}}
      - uses: strip
    test:
      pipeline:
        - uses: python/import
          with:
            python: python${{range.key}}
            import: ${{vars.pypi-package}}

  - name: py3-supported-${{vars.pypi-package}}
    description: meta package providing ${{vars.pypi-package}} for supported python versions.
    dependencies:
      runtime:
        - py3.10-${{vars.pypi-package}}
        - py3.11-${{vars.pypi-package}}
        - py3.12-${{vars.pypi-package}}
        - py3.13-${{vars.pypi-package}}

update:
  enabled: true
  github:
    identifier: pydantic/jiter
    tag-filter: v
    strip-prefix: v
