package:
  name: ruby3.4-timeout
  version: 0.4.2
  epoch: 0
  description: Auto-terminate potentially long-running operations in Ruby.
  copyright:
    - license: Ruby
    - license: BSD-2-Clause

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - git
      - ruby-${{vars.rubyMM}}
      - ruby-${{vars.rubyMM}}-dev

pipeline:
  - uses: git-checkout
    with:
      expected-commit: 2f5252299403e00135b694455fb31a2bded32cd5
      repository: https://github.com/ruby/timeout
      tag: v${{package.version}}

  - uses: ruby/build
    with:
      gem: ${{vars.gem}}

  - uses: ruby/install
    with:
      gem: ${{vars.gem}}
      version: ${{package.version}}

  - uses: ruby/clean

vars:
  gem: timeout

update:
  enabled: true
  github:
    identifier: ruby/timeout
    strip-prefix: v

var-transforms:
  - from: ${{package.name}}
    match: ^ruby(\d\.\d+)-.*
    replace: $1
    to: rubyMM
