package:
  name: secrets-store-csi-driver-provider-gcp
  version: 1.7.0
  epoch: 0
  description: Google Secret Manager provider for the Secret Store CSI Driver.
  copyright:
    - license: Apache-2.0

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - go
      - openssf-compiler-options
      - wolfi-baselayout

pipeline:
  - uses: git-checkout
    with:
      expected-commit: c640ef4395f9953ea93516e18f968769bcc52776
      repository: https://github.com/GoogleCloudPlatform/secrets-store-csi-driver-provider-gcp
      tag: v${{package.version}}

  - runs: |
      mkdir -p ${{targets.destdir}}/usr/bin/

      go build \
        -ldflags "-w -extldflags '-static' -X 'main.version=${{package.version}}'" \
        -o ${{targets.destdir}}/usr/bin/secrets-store-csi-driver-provider-gcp .

  - uses: strip

update:
  enabled: true
  manual: false
  github:
    identifier: GoogleCloudPlatform/secrets-store-csi-driver-provider-gcp
    strip-prefix: v

test:
  pipeline:
    # AUTOGENERATED
    - runs: |
        secrets-store-csi-driver-provider-gcp --help
