package:
  name: slsa-verifier
  version: 2.6.0
  epoch: 6
  description: Verify provenance from SLSA compliant builders
  copyright:
    - license: Apache-2.0

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/slsa-framework/slsa-verifier
      tag: v${{package.version}}
      expected-commit: 3714a2a4684014deb874a0e737dffa0ee02dd647

  - uses: go/bump
    with:
      deps: github.com/sigstore/sigstore-go@v0.6.1 github.com/theupdateframework/go-tuf/v2@v2.0.1 golang.org/x/crypto@v0.31.0
      replaces: github.com/docker/docker=github.com/docker/docker@v26.1.5+incompatible
      modroot: .

  - uses: go/build
    with:
      packages: ./cli/slsa-verifier
      modroot: .
      output: slsa-verifier
      ldflags: -X sigs.k8s.io/release-utils/version.gitVersion=${{package.version}} -X sigs.k8s.io/release-utils/version.gitCommit=$(git rev-parse HEAD) -X sigs.k8s.io/release-utils/version.buildDate=$(date ${SOURCE_DATE_EPOCH:+ -d@${SOURCE_DATE_EPOCH}} "+%Y-%m-%dT%H:%M:%SZ")

update:
  enabled: true
  github:
    identifier: slsa-framework/slsa-verifier
    strip-prefix: v

test:
  pipeline:
    # AUTOGENERATED
    - runs: |
        slsa-verifier --help
        slsa-verifier version
