package:
  name: sops
  version: 3.9.2
  epoch: 1
  description: Simple and flexible tool for managing secrets
  copyright:
    - license: MPL-2.0

environment:
  contents:
    packages:
      - busybox
      - ca-certificates-bundle
      - go

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/getsops/sops
      tag: v${{package.version}}
      expected-commit: bb710f3d6c34aa1d805c3e42462c33485abc9d2f

  # 3.9.2 update requires a tidy for some reason, we may be able to remove this in a later version.
  # https://github.com/wolfi-dev/os/pull/35658
  - runs: |
      cd cmd/sops
      go mod tidy

  - uses: go/bump
    with:
      deps: golang.org/x/crypto@v0.31.0
      modroot: .

  - uses: go/build
    with:
      modroot: .
      packages: ./cmd/sops
      output: sops

  - uses: strip

update:
  enabled: true
  github:
    identifier: getsops/sops
    strip-prefix: v

test:
  environment:
    contents:
      packages:
        - gpg
        - gpg-agent
  pipeline:
    - uses: git-checkout
      with:
        repository: https://github.com/getsops/sops
        tag: v${{package.version}}
        expected-commit: bb710f3d6c34aa1d805c3e42462c33485abc9d2f
    - name: version check
      runs: |
        sops --version
        sops --help
    - name: decrypt
      runs: |
        gpg-agent --daemon
        gpg --import pgp/sops_functional_tests_key.asc

        cd examples/all_in_one
        sops decrypt config/secret.enc.json
