package:
  name: spark-operator
  version: 2.0.2
  epoch: 2
  description: Kubernetes operator for managing the lifecycle of Apache Spark applications on Kubernetes.
  copyright:
    - license: Apache-2.0
  dependencies:
    runtime:
      - procps

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - git
      - go
      - openssf-compiler-options
      - tini

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/kubeflow/spark-operator
      tag: v${{package.version}}
      expected-commit: ef9a2a134b80f8c5368db53615d9aa766c67ad0a

  - uses: go/bump
    with:
      deps: k8s.io/kubernetes@v1.30.3 golang.org/x/crypto@v0.31.0

  - uses: go/build
    with:
      packages: ./cmd/
      output: spark-operator

  - uses: strip

subpackages:
  - name: "sparkctl"
    pipeline:
      - uses: go/build
        with:
          packages: ./sparkctl
          output: sparkctl
      - uses: strip
    test:
      pipeline:
        - runs: |
            sparkctl --version
            sparkctl --help

  - name: spark-operator-oci-entrypoint
    pipeline:
      - runs: |
          mkdir -p ${{targets.subpkgdir}}/usr/bin/
          cp entrypoint.sh ${{targets.subpkgdir}}/usr/bin/
          chmod 0755 ${{targets.subpkgdir}}/usr/bin/entrypoint.sh
          # entrypoints expects tini to be on /sbin/tini
          # https://github.com/GoogleCloudPlatform/spark-on-k8s-operator/blob/master/entrypoint.sh#LL27C5-L27C19
          ln -s /sbin/tini ${{targets.subpkgdir}}/usr/bin/tini
    dependencies:
      runtime:
        - openssl
        - tini
        - posix-libc-utils
        - coreutils
    test:
      pipeline:
        - runs: |
            tini --version
            tini -h

update:
  enabled: true
  github:
    identifier: kubeflow/spark-operator
    strip-prefix: v
    use-tag: true

test:
  pipeline:
    # AUTOGENERATED
    - runs: |
        spark-operator --help
