package:
  name: spin
  version: 3.1.1
  epoch: 0
  description: "Spin is the open source developer tool for building and running serverless applications powered by WebAssembly."
  copyright:
    - license: Apache-2.0
  resources:
    cpu: 20
    memory: 8Gi
  dependencies:
    runtime:
      - git

environment:
  contents:
    packages:
      - bash
      - build-base
      - busybox
      - ca-certificates-bundle
      - cmake
      - openssf-compiler-options
      - openssl-dev
      - rustup
      - wolfi-base
  environment:
    VERGEN_IDEMPOTENT: "true"
    SOURCE_DATE_EPOCH: "315532900"

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/fermyon/spin
      tag: v${{package.version}}
      expected-commit: aa919ce36a5f6c45e6c9b66bcd94657281f44bf3

  - name: Configure and build
    runs: |
      # This build requires the stable version of rust, managed by rustup, because it requires a few other toolchains too.
      rustup install stable
      rustup target add wasm32-wasi
      rustup target add wasm32-unknown-unknown

      # This is a bit of a hack, but it's the easiest way to get the right version of rustc and cargo in the path.
      export PATH="$HOME/.rustup/toolchains/stable-${{build.arch}}-unknown-linux-gnu/bin:$PATH"

      if [ "${{build.arch}}" = "aarch64" ]; then
          echo '[build]' >> .cargo/config
          echo 'rustflags = ["-Ctarget-feature=+fp16"]' >> .cargo/config
      fi

      cargo build --release

      mkdir -p ${{targets.destdir}}/usr/bin/
      mv target/release/spin ${{targets.destdir}}/usr/bin/

  - uses: strip

update:
  enabled: true
  github:
    identifier: fermyon/spin
    strip-prefix: v

test:
  pipeline:
    # AUTOGENERATED
    - runs: |
        spin --version
        spin --help
