package:
  name: src
  version: 5.10.0
  epoch: 1
  description: Sourcegraph CLI
  copyright:
    - license: Apache-2.0
  dependencies:
    runtime:
      - ca-certificates-bundle
      - git

environment:
  contents:
    packages:
      - busybox
      - ca-certificates-bundle
      - go
      - libx11-dev

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/sourcegraph/src-cli
      expected-commit: 4f198d08d056304ae5f20a692cca70c77c515fef
      tag: ${{package.version}}

  - uses: go/bump
    with:
      # The replacement must run before the initial tidy, otherwise the repo resolution fails and so does the build. The build will run tidy.
      skip-initial-tidy: true
      deps: github.com/golang/protobuf@v1.5.4 k8s.io/api@v0.27.13 k8s.io/apimachinery@v0.27.13 k8s.io/client-go@v0.27.13 k8s.io/metrics@v0.27.13 golang.org/x/crypto@v0.31.0
      replaces: github.com/sourcegraph/sourcegraph/lib=github.com/sourcegraph/sourcegraph-public-snapshot/lib@v0.0.0-20240709083501-1af563b61442

  - uses: go/build
    with:
      packages: ./cmd/src
      output: src
      ldflags: "-s -w -X github.com/sourcegraph/src-cli/internal/version.BuildTag=${{package.version}}"

  - uses: strip

update:
  enabled: true
  github:
    identifier: sourcegraph/src-cli

test:
  pipeline:
    - name: Verify src installation
      runs: |
        src version || exit 1
        src --help
    - name: Display src CLI help
      runs: |
        src -h || exit 1
