package:
  name: tailscale
  version: 1.78.1
  epoch: 1
  description: The easiest, most secure way to use WireGuard and 2FA.
  copyright:
    - license: BSD-3-Clause

environment:
  contents:
    packages:
      - bash
      - busybox
      - ca-certificates-bundle
      - curl
      - go
      - openssf-compiler-options

pipeline:
  - uses: git-checkout
    with:
      expected-commit: c80eb698d5057b04d826b5ae2004d4c464ae28f6
      repository: https://github.com/tailscale/tailscale
      tag: v${{package.version}}

  - uses: go/bump
    with:
      deps: golang.org/x/crypto@v0.31.0

  - runs: |
      ./build_dist.sh tailscale.com/cmd/tailscale
      ./build_dist.sh tailscale.com/cmd/tailscaled

  - runs: |
      install -Dm755 ${{package.name}} ${{targets.destdir}}/usr/bin/tailscale
      install -Dm755 ${{package.name}}d ${{targets.destdir}}/usr/sbin/tailscaled

  - uses: strip

update:
  enabled: true
  github:
    identifier: tailscale/tailscale
    strip-prefix: v

test:
  pipeline:
    - name: Verify Tailscale Version
      runs: |
        tailscale version
        tailscale --version
        tailscale --help
        tailscaled --version
        tailscaled --help
    - name: Tailscale Daemon Test
      runs: |
        tailscaled -tun=userspace-networking -socket=tailscaled.socket &
        sleep 2
        tailscale --socket=tailscaled.socket status | grep -q 'Logged out.'
