package:
  name: terraform-provider-aws
  version: 5.80.0
  epoch: 1
  description: Terraform AWS provider
  copyright:
    - license: MPL-2.0
  resources:
    cpu: 16
    memory: 40Gi
  dependencies:
    runtime:
      - terraform
      - terraform-compat
      - terraform-local-provider-config

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/hashicorp/terraform-provider-aws
      tag: v${{package.version}}
      expected-commit: 9273b07bad89e6aa730482f3a8fc7840b38b9d68

  # At the time of writing (12/24), we can't use go/bump on this project, due
  # to 'godebug' directive being defined in the go.mod. We'll need updates to
  # go/bump to handle this - internal DYDX ticket filed.
  - uses: patch
    with:
      patches: GHSA-v778-237x-gjrc.patch

  - runs: go mod tidy

  - uses: go/build
    with:
      packages: .
      output: terraform-provider-aws

  - runs: |
      GOARCH=$(go env GOARCH)
      mkdir -p "${{targets.destdir}}"/terraform/provider-mirror/registry.terraform.io/hashicorp/aws/${{package.version}}/linux_${GOARCH}/
      ln -s "${{targets.destdir}}"/usr/bin/terraform-provider-aws \
          "${{targets.destdir}}"/terraform/provider-mirror/registry.terraform.io/hashicorp/aws/${{package.version}}/linux_${GOARCH}/terraform-provider-aws_v${{package.version}}_x5

update:
  enabled: true
  github:
    identifier: hashicorp/terraform-provider-aws
    strip-prefix: v

test:
  pipeline:
    # AUTOGENERATED
    - runs: |
        terraform-provider-aws --help
