package:
  name: tfsec
  version: 1.28.11
  epoch: 1
  description: Security scanner for your Terraform code
  copyright:
    - license: MIT

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - git
      - go

pipeline:
  - uses: git-checkout
    with:
      expected-commit: 6444d311bb1def7c8413053f577d4f0b5b9ee338
      repository: https://github.com/aquasecurity/tfsec
      tag: v${{package.version}}

  - uses: go/bump
    with:
      deps: golang.org/x/crypto@v0.31.0

  - uses: go/build
    with:
      packages: ./cmd/tfsec
      output: tfsec
      ldflags: -X github.com/aquasecurity/tfsec/version.Version=v${{package.version}} -s -w -extldflags '-fno-PIC -static'

  - uses: go/build
    with:
      packages: ./cmd/tfsec-checkgen
      output: tfsec-checkgen
      ldflags: -X github.com/aquasecurity/tfsec/version.Version=v${{package.version}} -s -w -extldflags '-fno-PIC -static'

  - uses: strip

update:
  enabled: true
  github:
    identifier: aquasecurity/tfsec
    use-tag: true
    strip-prefix: v

test:
  pipeline:
    - runs: |
        tfsec --version
        tfsec --version | grep v${{package.version}}
        tfsec --help
        tfsec-checkgen --help
