package:
  name: wit-bindgen
  version: 0.36.0
  epoch: 1
  description: "A language binding generator for WebAssembly interface types"
  copyright:
    - license: Apache-2.0

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - cargo-auditable
      - openssf-compiler-options
      - rust
      - wolfi-base

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/bytecodealliance/wit-bindgen
      tag: v${{package.version}}
      expected-commit: d1387cc70f67c53e31e2668a30a1e4fc8bdcb95a

  - uses: rust/cargobump

  - name: Configure and build
    runs: |
      cargo auditable build --release -vv
      mkdir -p ${{targets.destdir}}/usr/bin/
      mv target/release/wit-bindgen ${{targets.destdir}}/usr/bin/

  - uses: strip

update:
  enabled: true
  ignore-regex-patterns:
    - wit-bindgen-cli-*
  github:
    identifier: bytecodealliance/wit-bindgen
    strip-prefix: v

test:
  pipeline:
    # AUTOGENERATED
    - runs: |
        wit-bindgen --version
        wit-bindgen --help
