package:
  name: xfsprogs
  version: 6.12.0
  epoch: 0
  description: XFS filesystem utilities
  copyright:
    - license: LGPL-2.1-or-later

environment:
  contents:
    packages:
      - attr-dev
      - autoconf
      - automake
      - bash
      - build-base
      - busybox
      - ca-certificates-bundle
      - file
      - gettext-dev
      - inih-dev
      - libtool
      - linux-headers
      - openssf-compiler-options
      - readline-dev
      - userspace-rcu-dev
      - userspace-rcu-static
      - util-linux-dev

pipeline:
  - uses: fetch
    with:
      uri: https://mirrors.edge.kernel.org/pub/linux/utils/fs/xfs/xfsprogs/xfsprogs-${{package.version}}.tar.xz
      expected-sha512: 020810b4a261f4ab4eb94aae813f22b26bb9f17705967198189509e684422361dd80af938e4a77cf326353d5d61d5aeaaee9a34e8a7b8ed1dddd63b7ad1b0510

  - uses: autoconf/configure
    with:
      opts: |
        --sbindir=/usr/sbin \
        --enable-gettext=no

  - uses: autoconf/make

  - runs: |
      make DIST_ROOT="${{targets.destdir}}" PKG_ROOT_SBIN_DIR="/usr/sbin" PKG_ROOT_LIB_DIR="/usr/lib64" install install-dev

      find ${{targets.destdir}} -name '*.la' -print -exec rm \{} \;

      chown -R root:root "${{targets.destdir}}"/*

  - uses: strip

subpackages:
  - name: xfsprogs-dev
    description: "headers for xfsprogs"
    pipeline:
      - uses: split/dev

  - name: xfsprogs-libs
    description: "libraries for xfsprogs"
    pipeline:
      - runs: |
          mkdir -p "${{targets.subpkgdir}}"/usr/lib64
          mv "${{targets.destdir}}"/usr/lib64/lib*.so.* "${{targets.subpkgdir}}"/usr/lib64

  - name: xfsprogs-doc
    description: "xfsprogs manpages"
    pipeline:
      - uses: split/manpages

  - name: xfs-scrub
    description: "xfs-scrub attempts to check and repair all metadata in a mounted XFS filesystem"
    dependencies:
      runtime:
        - xfsprogs
        - python3
    pipeline:
      - runs: |
          mkdir -p "${{targets.subpkgdir}}"/usr/share/xfsprogs
          mv "${{targets.destdir}}"/usr/share/xfsprogs/xfs_scrub* "${{targets.subpkgdir}}"/usr/share/xfsprogs/

          mkdir -p "${{targets.subpkgdir}}"/usr/sbin
          mv "${{targets.destdir}}"/usr/sbin/xfs_scrub* "${{targets.subpkgdir}}"/usr/sbin/

update:
  enabled: true
  release-monitor:
    identifier: 5188

test:
  environment:
    contents:
      packages:
        - util-linux
        - file
  pipeline:
    - name: "Check xfs_repair version"
      runs: |
        xfs_repair -V
        xfs_admin version
        xfs_admin help
        xfs_bmap -v
        xfs_estimate version
        xfs_estimate help
        xfs_fsr version
        xfs_fsr help
        xfs_mkfile version
        xfs_mkfile help
        xfs_quota version
        xfs_quota help
    - name: "Check mkfs.xfs version"
      runs: |
        mkfs.xfs -V
    - name: "Test basic xfs_db functionality"
      runs: |
        dd if=/dev/zero of=xfs.img bs=1M count=300
        mkfs.xfs xfs.img
        xfs_db -c 'sb 0' -c 'p' xfs.img | grep 'magicnum'
    - name: "Test xfs_info functionality"
      runs: |
        dd if=/dev/zero of=xfs.img bs=1M count=300
        mkfs.xfs xfs.img
        xfs_info xfs.img | grep -E 'naming\s*=\s*version\s*2'
    - name: "Test xfs_metadump functionality"
      runs: |
        dd if=/dev/zero of=xfs.img bs=1M count=300
        mkfs.xfs xfs.img
        xfs_metadump xfs.img xfs_metadata.img
        file xfs_metadata.img | grep 'XFS filesystem'
    - name: "Test xfs_admin functionality"
      runs: |
        dd if=/dev/zero of=xfs.img bs=1M count=300
        mkfs.xfs xfs.img
        xfs_admin -L "TestXFS" xfs.img
        xfs_admin -l xfs.img | grep 'TestXFS'
    - uses: test/ldd-check
      with:
        files: /usr/lib64/libhandle.so
