package:
  name: xz
  version: 5.6.3
  epoch: 2
  description: "Library and CLI tools for XZ and LZMA compressed files"
  copyright:
    - license: GPL-3.0-or-later

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - openssf-compiler-options
      - wolfi-baselayout

pipeline:
  - uses: fetch # use fetch instead of git-checkout else there is a circular dependency with git
    with:
      uri: https://github.com/tukaani-project/xz/releases/download/v${{package.version}}/xz-${{package.version}}.tar.gz
      expected-sha256: b1d45295d3f71f25a4c9101bd7c8d16cb56348bbef3bbc738da0351e17c73317

  - name: Configure
    runs: |
      ./configure \
         --host=${{host.triplet.gnu}} \
         --target=${{host.triplet.gnu}} \
         --prefix=/usr \
         --datadir=/usr/share

  - uses: autoconf/make

  - uses: autoconf/make-install

  - uses: strip

subpackages:
  - name: "xz-dev"
    description: "xz headers"
    pipeline:
      - uses: split/dev
    dependencies:
      runtime:
        - xz
    test:
      pipeline:
        - uses: test/pkgconf

  - name: "xz-doc"
    description: "xz documentation"
    pipeline:
      - uses: split/manpages
      - runs: |
          mkdir -p ${{targets.subpkgdir}}/usr/share/doc
          mv ${{targets.destdir}}/usr/share/doc/xz ${{targets.subpkgdir}}/usr/share/doc/xz

test:
  pipeline:
    - name: Verify xz installation
      runs: |
        xz --version || exit 1
        lzcat --version
        lzcat --help
        lzcmp --version
        lzcmp --help
        lzdiff --version
        lzdiff --help
        lzegrep --version
        lzegrep --help
        lzfgrep --version
        lzfgrep --help
        lzgrep --version
        lzgrep --help
        lzless --version
        lzless --help
        lzma --version
        lzma --help
        lzmadec --version
        lzmadec --help
        lzmainfo --version
        lzmainfo --help
        lzmore --version
        lzmore --help
        unlzma --version
        unlzma --help
        unxz --version
        unxz --help
        xz --help
        xzcat --version
        xzcat --help
        xzcmp --version
        xzcmp --help
        xzdec --version
        xzdec --help
        xzdiff --version
        xzdiff --help
        xzegrep --version
        xzegrep --help
        xzfgrep --version
        xzfgrep --help
        xzgrep --version
        xzgrep --help
        xzless --version
        xzless --help
        xzmore --version
        xzmore --help
    - name: Basic xz compression and decompression test
      runs: |
        echo "Hello, Wolfi!" > data.txt
        cp data.txt data.bak
        xz -z data.txt
        xz -t data.txt.xz
        xz -d data.txt.xz
        cmp data.txt data.bak
    - uses: test/ldd-check
      with:
        files: |-
          /usr/lib/liblzma.so.5
          /usr/lib/liblzma.so.5.6.3

update:
  enabled: true
  github:
    identifier: tukaani-project/xz
    strip-prefix: v
