package:
  name: yara-x
  version: 0.12.0
  epoch: 0
  description: "A rewrite of YARA in Rust."
  copyright:
    - license: BSD-3-Clause

environment:
  contents:
    packages:
      - build-base
      - ca-certificates-bundle
      - openssl-dev
      - perl
      - rust
      - wolfi-base

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/VirusTotal/yara-x
      expected-commit: d2b8358879c009f41f0e14847681f2f8dbe624cf
      tag: v${{package.version}}

  - runs: cargo install cargo-c --features=vendored-openssl

  - runs: cargo cinstall -p yara-x-capi --release --prefix=/usr --pkgconfigdir=/usr/lib/pkgconfig --includedir=/usr/include --libdir=/usr/lib

subpackages:
  - name: yara-x-compat
    dependencies:
      runtime:
        - ${{package.name}}
    pipeline:
      - runs: |
          mkdir -p ${{targets.subpkgdir}}/usr/local/include
          mkdir -p ${{targets.subpkgdir}}/usr/local/lib
          mkdir -p ${{targets.subpkgdir}}/usr/local/lib/pkgconfig
          cp -a /usr/lib/libyara_x_capi* ${{targets.subpkgdir}}/usr/local/lib/
          cp /usr/lib/pkgconfig/yara_x_capi.pc ${{targets.subpkgdir}}/usr/local/lib/pkgconfig/
          cp /usr/include/yara_x.h ${{targets.subpkgdir}}/usr/local/include/

update:
  enabled: true
  github:
    identifier: VirusTotal/yara-x
    strip-prefix: v

test:
  environment:
    contents:
      packages:
        - gcc
        - glibc-dev
        - pkgconf-dev
        - ${{package.name}}-compat
  pipeline:
    - runs: |
        cat <<EOF > test.c
        #include <yara_x.h>
        int main() {
            YRX_RULES* rules;
            yrx_compile("rule dummy { condition: true }", &rules);
            yrx_rules_destroy(rules);
        }
        EOF

        gcc `pkg-config --cflags yara_x_capi` `pkg-config --libs yara_x_capi` test.c
