package:
  name: zizmor
  version: 0.9.1
  epoch: 0
  description: "A static analysis tool for GitHub Actions"
  copyright:
    - license: MIT

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/woodruffw/zizmor
      expected-commit: f281e0c26af4ac30d5d001d38e4222dcd51eb51c
      tag: v${{package.version}}

  - uses: cargo/build
    with:
      output: ${{package.name}}

  - uses: strip

update:
  enabled: true
  github:
    identifier: woodruffw/zizmor
    strip-prefix: v

test:
  pipeline:
    - runs: |
        zizmor --version
        zizmor --help
